### ISSUE TITLE
BookNumber leading 0

### ISSUE THREAD

**Issue by nevrion** [yermak/AudioBookConverter#101]
First of all, thank you very much for this great tool!

Is there any way to keep leading zeros in the book number when saving or at least include them in the file name?

Example :
001 always becomes 1

I have series with over 100 episodes and would be happy to sort them this way.

Excuse my bad English.

**Comment by yermak** [comment]
Similar issue was discussed already, thank you for raising separate ticket.
I will add this at some point

**Comment by yermak** [comment]
starting from version 5.5.14 you should be able to do so, find AudioBookConverter.property file, normally locatated in ApplicationData folder.
In section _filename_format_ find <BOOK_NUMBER; format\="%,02d"> - 02 means how total numbers it will have in suggested output file name, change to 03d and restart the program.
Same could be done with chapter and parts name.
