### ISSUE TITLE
Build fails on Windows 10 without Wix tools installed

### ISSUE THREAD

**Issue by stormdb** [yermak/AudioBookConverter#104]
Build fails on Windows 10 with a message that Wix tools are missing.
[Building from source](https://github.com/yermak/AudioBookConverter/wiki/Building-from-source) doesn't mention Wix tools

**Comment by stormdb** [comment]
Relates to #120

**Comment by yermak** [comment]
Building from source describes build under linux.
Wix is described as dependency at in jpackage documentation https://openjdk.java.net/jeps/343.

Anyway wix will be removed from default build script
