### ISSUE TITLE
Release versions are not build automatically

### ISSUE THREAD

**Issue by stormdb** [yermak/AudioBookConverter#107]
Project has no CI/CD pipeline to build release versions automatically.
Pipeline must be triggered on any changes in "master" branch,

**Comment by stormdb** [comment]
Duplicated by issues #122, #121 and #120 .

**Comment by yermak** [comment]
Let's keep this issue open is it's more related to overall CI/CD orchestration. I.e. policies when and how CI/CD is triggered.
I would suggest that change in master (or development) triggers general build, if build passes tests, then it creates tag with build version. On tag creation separate pipeline is triggered to produce binaries for all platforms.
Thoughs?

**Comment by yermak** [comment]
Finally fixed in build 5.5.1
