### ISSUE TITLE
File is showing 21mins instead of 31 hrs, and cannot make chapters

### ISSUE THREAD

**Issue by carverhaines** [yermak/AudioBookConverter#127]
I have added one 31 hour mp3 file, and everytime I export it is exports a 21min file. Also, when I go to chapters and click split and combine, nothing happens. Am I doing something wrong?

**Comment by yermak** [comment]
Hi,
I assume you watched tutorial video https://www.youtube.com/watch?v=N7JrujMfids and read FAQ - and this did not help.
As for your file - you need to find the way to share it with me - I could have a look.

**Comment by carverhaines** [comment]
Ok, I think I sent it to the right email address.

Ah, I see, 'split' does not create new chapters, only splits sections from existing files. Would there be a way to "add chapters at __min intervals"?

**Comment by yermak** [comment]
Hi! thank you. received the link.
I will have a look - most likely over the weekend, have few things in progress now.

As for split by interval, it's quite simple to do technically, but I'm not sure how many people would use this feature and why.
I would understand scenario when you have got 1 huge file and no chapters and you would like to cut it as at specific positions, i.e. set chapter marks manually. (Still concerned how many people would do this). But why would you look for splitting at specific interval?

**Comment by yermak** [comment]
Hi again,
It's easier then i though.
Your mp3 file contains chapter information, like requested in #100.
I was not sure about the need to support this in output, however, program is trying to be smart and read it even from mp3. This would not be a problem, however chapter information is broken somehow, and only chapter 1 survived in your file, which is exactly your 21mins.
It's difficult to predict all possible broken files, however, i will think about possibility to check total chapter length and total file duration - not sure what program should do then...

You could fix your specific file with simple command (using ffmpeg provided in distribution)

`ffmpeg -i YOUR_FILE  -map_chapters -1  -c:a copy OUT_FILE.mp3`

After this broken chapter information will be lost and file will be imported as normal mp3.

**Comment by yermak** [comment]
Combine and split mostly designed for opposite use case, when chapter is split in multiple files - you select them and press combine. 
If you grouped several files into chapter by mistake - you can select one where you would like to split (create chapter) and press split.

Manual split by time is not yet there (and not sure when/if it will be done)

On a separate note: I was thinking about importing chapter information from text file as this could be much more convenient way - i.e. Chapter name - start time; this will be way more easier way to create chapters...

**Comment by carverhaines** [comment]
Thanks for the info.

I used to use the "split into 10 min chapters" function all the time in Chapter and Verse (when it was still working in Win10 before updates), because I want to be able to skip through chapters quickly to find a spot where I left off, even if the chapters don't correlate to actual chapters in the book.

**Comment by yermak** [comment]
I hope you resolved your issue. Closing this one as i created separate feature requests.

**Comment by guategeek** [comment]
> On a separate note: I was thinking about importing chapter information from text file as this could be much more convenient way - i.e. Chapter name - start time; this will be way more easier way to create chapters...

I would love for this, and/or the option to set a chapter at a time interval in the software. I also found the "Split" and "Join" confusing as I was trying to add chapters to one large file. 

At the moment I have to take a single audio file book into Audacity and find the chapters, then cut that part of the file out and save it as a new file. So that I can finally combine them all back together into the m4b file with correct chapters. Being able to use a time code to set the chapters would save me the hassle of splitting the file to then recombine it.
