### ISSUE TITLE
Automatic split book by chapters based on time intervals

### ISSUE THREAD

**Issue by yermak** [yermak/AudioBookConverter#147]
If book does not contain any chapter information, i.e. single mp3/mwa file or CD rip with no track. User may prefer to break book into chapter for simple navigation, i.e. every 10 mins or every 60 mins.
I'm not quite sure this is really useful feature, so need to think and discuss.
Similar issue described at #127

**Comment by mp3096** [comment]
can u add every 50 chapter it makes new file so on.

**Comment by LavaTiger99** [comment]
I agree, this is the main thing holding me back from using this feature. Many of my audiobooks are large MP3's with no chapter info.

**Comment by yermak** [comment]
It would be great if someone could help to think how this feature should work and how app should behave.
I.e. what about if have existing chapters: shall program break into new chapters structure i.e. 30min per chapter or break every chapter by 30 mins (if it's longer).
Or shall program offer to break by intervals only if 1 file added (and it does not have chapter info - i.e. large m4b with no chapter)?

**Comment by LavaTiger99** [comment]
How about "Clear all chapters and create new chapters at x y" where x is a number and y is seconds/minutes/hours?
Create these chapters AFTER the merging of multiple individual MP3 files.

**Comment by LavaTiger99** [comment]
Since most of it's utility is for files that do not already have chapters.

**Comment by yermak** [comment]
@LavaTiger99 , @mp3096 , 

This feature is implemented in version 5.5.10.

You need to import chapters and do right-click on mp3 file you have in chapter and select "Sub-tracks"
You could either auto-wrap sub-tracks with chapters, or create sub-tracks in chapter and manage them manually.
