### ISSUE TITLE
Program indexes all photos on my computer. **ALL**

### ISSUE THREAD

**Issue by Darkwolf1515** [yermak/AudioBookConverter#153]
It also seemingly trys to add all photos to my book, leading it to never finish converting.

**Comment by yermak** [comment]
Hi, this is possbile in scenario when you input files are in root of drive C or in your home directory.
Try to place input files into separate folder and show it as source.

There is a reason for such behaviur, i have seen quite often that cover was either in directory with mp3 or sometimes in subdirectory.
So program tries to be "smart" and add covers from mp3, from current directories and all subdirectories.

Prabably i need to put strict restriction and stop process after 3 or 5 images, as anything more then that is definitely misbihaviour.

**Comment by Darkwolf1515** [comment]
> 
> 
> Hi, this is possbile in scenario when you input files are in root of drive C or in your home directory.
> Try to place input files into separate folder and show it as source.
> 
> There is a reason for such behaviur, i have seen quite often that cover was either in directory with mp3 or sometimes in subdirectory.
> So program tries to be "smart" and add covers from mp3, from current directories and all subdirectories.
> 
> Prabably i need to put strict restriction and stop process after 3 or 5 images, as anything more then that is definitely misbihaviour.

The m4a files were in my downloads, but it indexed across my whole c drive, the cover was already embedded.

**Comment by yermak** [comment]
@Darkwolf1515,
Thanks for bug report, i will have a look.

As workaround i suggest to create special folder for your book and move files there.

**Comment by yermak** [comment]
@Darkwolf1515,
I will keep this open for now, as probably i need to do cut off on adding images otherwise it's entierly possible to add thousands of immages, which does not make much sense.

**Comment by yermak** [comment]
Fixed in next release, now number of artwork will be limited with 10.
