### ISSUE TITLE
Small Issue, 5.5.4

### ISSUE THREAD

**Issue by jjones3905** [yermak/AudioBookConverter#157]
Windows 10 version. The check for for new version always finds a new version.

**Comment by yermak** [comment]
@jjones3905 , thanks.
This is due to new release process, will be fixed soon. Sometimes it will show there is a new version

**Comment by jjones3905** [comment]
In the log: New version found: AudioBookConverter-5.5.3 :)

**Comment by yermak** [comment]
Fixed in version 5.5.7
