### ISSUE TITLE
Chapter Naming

### ISSUE THREAD

**Issue by Asuryan34** [yermak/AudioBookConverter#172]
Hello.

Thank you for your work.

I'm not sure if it's something possible or not. It least, I have no idea how to do it and don't see any option for that.

I have a serie of .mp3 that I would like to convert in an .m4b file. Each .mp3 have metedata with the chapter's title. When I convert it, I lose it and have only "Chapter 001 - 00:11:30.

Is it possible to have the proper title embeded in the m4b file ( Chapter 01 : title - 00:11:30) ??

**Comment by yermak** [comment]
Hi,
You can do this with program. 
After adding files, click "Chapters", then select any chapter end click "Edit", in edit window in drop down of list select "title". In preview you should see correct chapter name. Don't forget to click checkbox "apply to all chapters". And you should see titles of all chapters refreshed.

**Comment by Asuryan34** [comment]
Hello.

Thank you. 
I was clicking on Edit without selecting a chapter before :) 

Thx again :)
