### ISSUE TITLE
macOS error opening app: "ConverterApplication.app" is damaged

### ISSUE THREAD

**Issue by red-ochre** [yermak/AudioBookConverter#173]
Running macOS Big Sur 11.0.1. Downloaded and opened "ConverterApplication-5.5.7.dmg". Dragged "ConverterApplication.app" to applications folder. Tried to open app and got the error.

![Screen Shot 2020-12-07 at 19 33 03](https://user-images.githubusercontent.com/16859090/101328705-7ace0680-38c4-11eb-9e18-8e93a53119b9.jpg)

**Comment by yermak** [comment]
Duplicates #152

It's not demaged, mac's security system prevents to run it.

Hi, sorry, i'm still trying to get it signed. Here is link - not sure if it works after latest update
https://www.howtogeek.com/205393/gatekeeper-101-why-your-mac-only-allows-apple-approved-software-by-default/#:~:text=To%20open%20an%20unsigned%20app%2C%20you%20need%20to%20right%2Dclick,with%20a%20valid%20developer%20signature.

The way to run it on Mac

Run Terminal:
```
cd  /Applications/ConverterApplication.app/Contents
MacOS/ConverterApplication
```

But please note that there are some other bugs in Mac version still, i.e. ArtWork may not work - but i will fix it soon.

**Comment by red-ochre** [comment]
Thanks Yermak. I'll wait till it's signed.

**Comment by dowobeha** [comment]
> Duplicates #152
> 
> It's not demaged, mac's security system prevents to run it.
> 
> Hi, sorry, i'm still trying to get it signed. Here is link - not sure if it works after latest update
> https://www.howtogeek.com/205393/gatekeeper-101-why-your-mac-only-allows-apple-approved-software-by-default/#:~:text=To%20open%20an%20unsigned%20app%2C%20you%20need%20to%20right%2Dclick,with%20a%20valid%20developer%20signature.
> 
> The way to run it on Mac
> 
> Run Terminal and execute following:
> 
> ```
> cd  /Applications/ConverterApplication.app/Contents
> MacOS/ConverterApplication
> ```
> 
> But please note that there are some other bugs in Mac version still, i.e. ArtWork may not work - but i will fix it soon.

Just attempted to follow these steps on macOS 10.15.7, and it still gives the same error message.

**Comment by thevoltagesource** [comment]
I ran in to this problem and found a solution that works under the latest version of Catalina.  Open System Preferences -> Security & Privacy -> Privacy, click the lock in the bottom left corner to unlock the settings, select Developer Tools on the left, and check the box for Terminal on the right.  Terminal will need to restart and then afterwards the above command will successfully run the app.

**Comment by yermak** [comment]
Duplicates #580

**Comment by yermak** [comment]
Beta for Mac OS X is available
https://github.com/yermak/AudioBookConverter/issues/580#issuecomment-2268738667
