### ISSUE TITLE
Converting aac (m4a) to audiobook

### ISSUE THREAD

**Issue by Nepumuk2000** [yermak/AudioBookConverter#19]
Hi,
thank you for this great piece of software. I have been looking for such a function quite some time after Chapter and Verse was discontinued.

Unfortunately, all my files are formatted as aac (*.m4a). Is there any chance you could implement a function to merge and convert those files? To my understanding (I'm no programmer), m4b is the same format as m4a but can provide additional information on the last position etc. If that is correct, my files "only" need to be merged, chapter marks be set and the file extension changed to *.m4b.

I would be pleased to hear your opinion.
Regards

**Comment by yermak** [comment]
Hi,
Thanks for your feedback.
m4a and m4b are exactly same format, as far as I'm concerned renaming them to m4b will do the job, so the only thing needed is just merging them.
I will have a look at it shortly, as i would prefer to have an option to bypass re-encoding if file is already in right format.
P.S. On a separate note if you have any other ideas please don't hesitate to share: i.e. How usefull to have advanced chapter management - current implementation is very stright forward and could be not accurate enough as mp3 lenght is always approximate and can vary especially with VBR encoding or ripping audio/mp3 CD.

**Comment by yermak** [comment]
Fixed in 3.1

**Comment by yermak** [comment]
Note: if you uncheck tickbox "Use quality of source files" your m4a files will be re-encoded. This will be slower and may lead to quality loss, however, you may do this for purpose to reduce size of the file.

**Comment by yermak** [comment]
There is major improvement for m4a support released in version 4.5.1
