### ISSUE TITLE
Installers fail on v 5.5.10

### ISSUE THREAD

**Issue by LavaTiger99** [yermak/AudioBookConverter#204]
Get an error on all versions of the installer on the latest release

**Comment by steelspace** [comment]
v 5.5.10 is said to be damaged on Mac OS (Mac Mini M1)

**Comment by yermak** [comment]
> v 5.5.10 is said to be damaged on Mac OS (Mac Mini M1)
@steelspace ,
Please see #173

**Comment by yermak** [comment]
If installer fails, please use Portable version, it just an archive - should help.
Or please give more details
