### ISSUE TITLE
Merge without re-encoding

### ISSUE THREAD

**Issue by crass00** [yermak/AudioBookConverter#206]
Would it be possible to add an option under the quality tab to not re-rencode the files.  I have files already in m4a format and re-encoding them again will loose quality unessesarily (well i think unessesarily, i don't know how the joining tools are working)

**Comment by yermak** [comment]
https://www.recoupler.com/products/audiobookconverter/faq

> Q: Does AudioBookConverter always re-encode? Is it possible to transcode w/o loosing quality.
> 
> A: AudioBookConverer tries to transcode if source codec and target default codec for selected format are same. I.e. m4a will likely be transcoded to m4b without re-encoding, however, if you select m4b wich is encoded with alac codec AudioBookConverter will re-encode it to aac even if you selected m4b as output. I'm still considering how to make transcoding/re-encoding more transparent to use.

**Comment by yermak** [comment]
I explained it several times in other threads, if I add option "no re-encoding" person could select different mp3 format as output for m4b source file, so this will make it quite unclear.

Default behaviour no-reencode if possible, however, if you change bitrate - program will re-encode, if currently it works differently - please report a bug

**Comment by crass00** [comment]
Thanks for that,  I was sure I had read that a few days ago but when I came back later after seeing that the encoder had changed from my source m4a files to the m4b file file, I couldn't see that faq answer (my bad).  Does the encoder show as being different becuase of the process even when no reencoding takes place.  I tried looking at the logs to tell but couldn't figure it out

**Comment by yermak** [comment]
Why do you thinks it shows different?
As far as i remember, decision about reencoding/transcoding is done in very last moment, when all factors are known (i.e. It can't transcode if you changed it to mono in last second). Then assuming output codec is same as input it will trascode. You will see it as it's very fast process.
However, if you selected presets or changed quality by other means it will reencode. 

P. S. Potential confusion could be with m4a files encoded by apple proprietary codec alac. They will be always reencoded.

**Comment by crass00** [comment]
looking at mp3tag and it shows the codec of one of the source files as qaac2.71 CoreAudioToolbox 7.10.9.0, AAC-LC Encoder etc but the joined file as Lavf58.45.100.

I don't touch any settings of the Quality tab before clicking start

**Comment by yermak** [comment]
Qaac is apple codec, most likely it uses alac.

to test you can find program ffprobe inside AudiobookConverter/app/external you could run it with single parameter of file you are checking and you will see real codec name as output.

**Comment by crass00** [comment]
the ffprobe command shows the same info as above so ffprobe must looks at the same thing mp3tag does.  The codec isn't alac it is definatly aac-lc (thats the option I wanted when transcoding to aac format originally)  here's an extra of ffprobe

    encoder         : qaac 2.71, CoreAudioToolbox 7.10.9.0, AAC-LC Encoder, TVBR q127, Quality 96
    Encoding Params : vers
  Duration: 00:00:04.13, start: 0.047891, bitrate: 123 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 117 kb/s (default)
    Metadata:
      creation_time   : 2021-01-21T19:42:02.000000Z

**Comment by zanhecht** [comment]
> Default behaviour no-reencode if possible, however, if you change bitrate - program will re-encode, if currently it works differently - please report a bug

If I take input m4bs that are 128kpbs and change the bitrate to 64kbps, it appears that it is still not re-encoding, as the output file is the same size as the sum of the input files.

**Comment by yermak** [comment]
Needs to be fixed together with #318

**Comment by yermak** [comment]
Partially fixed in #318. It's possible to force re-encode even when convert from m4b to m4b.

However, currently it's not possible to keep existing apple codec - i need to think how to bypass re-encoding for some codecs.

**Comment by yermak** [comment]
Now fully fixed. 
Several options to force re-encoding are possible: 
Auto - default behaviour, 
Alway re-encode - force to re-encode even for same codec, i.e. if you want to change bitrate or something else, 
Lazy - try to not re-encode if codecs are compatible, i.e. for apple alac codec for m4b files and vorbis for ogg files.

Program will detect if codec is compatible and bypass re-encoding, if there are other compatible codecs found - please report i will add them to compatibility list.

**Comment by yermak** [comment]
will be released in version 6
