### ISSUE TITLE
Duplicated bitrate options, result in unclear bitrate for output file, 128 encode is outright broken

### ISSUE THREAD

**Issue by ice44** [yermak/AudioBookConverter#209]
The bitrate options are bugged, 128 and 144 are duplicated, which results in an unclear bitrate for output file. I cannot encode in 128 at all, it forces 132 every time I select either of the 128 options because of this.

![Screenshot (15)](https://user-images.githubusercontent.com/22358562/105971943-1411d180-6059-11eb-97b4-f3643d21fd46.png)

**Comment by yermak** [comment]
Thanks. Is it always the issue?
Or some actions need to be done to create such behaviour?

**Comment by ice44** [comment]
Yes, it is always the issue.

**Comment by yermak** [comment]
Yes, you are right. I found it.
Duplication will be fixed shortly, however, I'm more worried about forcing to 132 everytime.
What output format do you select m4b or ogg?

**Comment by yermak** [comment]
#210 Fixed.
Will be available in next build
