### ISSUE TITLE
Merge titles of each file into chapter names

### ISSUE THREAD

**Issue by Nepumuk2000** [yermak/AudioBookConverter#22]
Hi,
thanks for the fast implementation of merging aac files into m4b - it works on my system and the result seems to be just as it should be.

As I now created my first audiobook with your program, I found the chapters named by standard tags. I would suggest a possibility to rename every chapter manually or to choose from all fields available in the original single file properties to be used as data source for the chapter names.

Before implementing this whole new function, I propose just using the title-tag of the original files as chapter name. Reason for that is that e.g. iTunes uses this field for naming the chapters when importing audiobooks. Thus, audiobooks could be imported first with some software and then be merged with AudioBookConverter without loosing the chapter information.

Regards

**Comment by yermak** [comment]
Hi,
Thanks for the idea.
Proper chapter support is on my todo list, it's good it materialized as an issue.
Quite often real book chapter is split between several source files or few real book chapters merged into single file, and title might be misleading.

I tried to do this in one of ther earlier versions, however, we need to consider that there are series of books and all chapters from the same series are displayed in single list on IBook app on IPhone.

Let me see if it worth reverting this feature back before proper implemation of chapters.

**Comment by yermak** [comment]
I did quick fix for this in v3.2.
If titles of files are empty then standard naming Chapter 1, etc. otherwise files titles will be used as chapter names.
