### ISSUE TITLE
Edit on Chapter Tab?

### ISSUE THREAD

**Issue by jjones3905** [yermak/AudioBookConverter#238]
Updated to 5.5.17 this morning.

When I load a directory of mp3s for a book (either by Add Directory on the File menu, or drag and drop), then switch to the Chapters tab and let the default chapter information generate, I'm no longer getting either an Edit button or Edit option in the Chapters menu. Thus, I can't open the dialogue box to let me select the title (file_name, etc) field as the chapter name.

See the attached image.

Did I just miss something where the functionality was moved?

Thanks,
Jon

![Chapter Tab](https://user-images.githubusercontent.com/17280961/109343628-40289a00-7833-11eb-9b0f-fc52f0cca308.png)

**Comment by yermak** [comment]
Hi,

Sorry i did some changes, and it seems it disappeared from menu.

You can still access a lot of action with right click. Edit should be there
