### ISSUE TITLE
Up and down buttons missing

### ISSUE THREAD

**Issue by metalollie** [yermak/AudioBookConverter#244]
Since the update, the buttons to move files up and and own, to rearrange the order are missing. The CTRL and Up/Down arrows do not work, so it can only be done from the menu.

**Comment by yermak** [comment]
Did you try mouse right click?

I will check shortcuts

**Comment by metalollie** [comment]
Hi,

Yes, right clicking works fine, however it’s impractical when moving a file
from top to bottom, for example, as I can end up doing the same thing 20 or
30 times. With the buttons it was much simpler as it’s a single click.
Also, the right click often only shows UP and DELETE, and not DOWN, usually
after a few clicks.

Cheers!

**Comment by yermak** [comment]
Let me think about usability again.
Thank you very much for feedback

**Comment by yermak** [comment]
New version 6.2.6 has new UI, so, now it's fixed

**Comment by metalollie** [comment]
Hi,

Can you tell me where to download the Mac edition of Audiobook Creator
please? I can’t find the link on GitHub, which is almost certainly my
fault, as I’m not really familiar with it.

Many thanks

Darren
