### ISSUE TITLE
Issue no#25, process not starting - still exits

### ISSUE THREAD

**Issue by seanyar** [yermak/AudioBookConverter#247]
I still have this issue. Using ver 5.5.18. Everything was working fine until today. Just as other comments in issue #25 that was closed. After dragging and dropping couple of MP3 files, nothing happens when you click on start. Stripped all tags and tried re-adding tags and attempted to convert - no luck. Each MP3 files on their own plays just fine in any player I tried.

Also tried reinstalling the application. No joy!

**Comment by skippybosco** [comment]
Is it any MP3 file or a specific MP3 file? Can you share one of the files you are having issues with somewhere and can attempt to reproduce the issue you are seeing.

**Comment by sewserious** [comment]
I am also having this issue. First popped up in 5.5.18. Uninstalled that version and went back to 5.5.17 and it worked for a while. This occurs on all mp3 files, not any specific one. I then went back to version 5.5.18 but no luck! I am converting mp3 files downloaded from librivox. Seemed to work for about 50 books or so both times and then quit. Tried the fixes listed in the old #25 with no luck. Please help!

**Comment by yermak** [comment]
I could suggest 2 options:
1) Go to C:\Users\%USERNAME%\Application Data\ and remove Configuration and Log folder called AudioBookConverter-x.y.z and try again.
2) You need to send me zipped content of this folder (there will be config and log file) to myusername @ gmail.com as well as mp3 files, so I could reproduce the issue.

**Comment by yermak** [comment]
Need to add this to FAQ section.
I can't understand yet, what part of configurations could be broken to prevent program from starting.
