### ISSUE TITLE
Ubuntu 20.04 LTS - libffi6 dependency issue

### ISSUE THREAD

**Issue by seanyar** [yermak/AudioBookConverter#248]
Installing the debian version on Ubuntu 20.04 LTS pops up 
"dpkg: dependency problems prevent configuration of audiobookconverter:
 audiobookconverter depends on libffi6; however:
  Package libffi6 is not installed."

As Ubuntu 20.04 LTS doesn't come with libffi6, and instead it comes with libffi7 already installed, is there any way to make it run with libffi7?

**Comment by yermak** [comment]
Hi,
As answered in discussion deb version works only for Ubuntu 18, after this they broke few dependencies.
I'm sorry, but ,ost likely i'm not going to fix it (too much efforts, not that many users) . I strongly recommend to switch to static build version.

**Comment by seanyar** [comment]
Thank you. That Worked.

**Comment by jeff47** [comment]
Sorry to deadpost - where is the static build available as a deb?  I saw the comments but there wasn't a link on where to find it.

**Comment by yermak** [comment]
Hi, static build is not available as deb.
Just download static build, unzip and run it - for newer version of ubuntu no proper installation is possible as of now.
