### ISSUE TITLE
Naming of chapters

### ISSUE THREAD

**Issue by ArcusVonSinus** [yermak/AudioBookConverter#26]
Hi, this app is awesome - basically exactly what I was looking for. 
I have just one small problem/request - would it be possible to offer an option to omit numbering from naming of chapters? 
I usually have the correct name in my title (f.e. "Chapter 01" or "Part 03"), and your app makes chapters with names "1. Chapter 01" or "3. Part 03".

Thanks!

**Comment by yermak** [comment]
That's an interesting topic.
As I also listen to series of books, and on iphone they all connected in single book. Where number of Book is used in the chapter.
It would be great to hear opinion how all it should from end-user-perspective. 

Also I think about an option to merge several files into signle chapter, with custom names - as found few books where chapters as split into multiple files with names like Chapter 01-1, Chapter 01-2.

Adding a checkbox - enable chapters numbering is not difficult - but it would be great to do it consistenly.

**Comment by ArcusVonSinus** [comment]
To be honest I have a specific usecase, so I do not know how to design the UI. But I would love the option to change the formatting of the chapters in the final m4b file, for example similar to the naming of filenames  (as in #[27])

**Comment by yermak** [comment]
I'm doing big rework on chapters now. It may solve your problem.

Can't do your request right now as concept of chapters will change.

I acknowledge that current naming is too basic.

I will update you once completed.

**Comment by ArcusVonSinus** [comment]
Awesome, thank you! :-)

**Comment by g4dget** [comment]
So I'm sure you're already aware of this, but chapters aren't working yet in version 4.0.

**Comment by yermak** [comment]
@g4dget,
I do believe that chapters work.
Please find short video demoing this https://youtu.be/N7JrujMfids 

@ArcusVonSinus, I belive it's not implemented.
Chapters should be configurable in config similar to file names.
`<if(BOOK_NUMBER)> Book <BOOK_NUMBER>. <endif>Chapter <CHAPTER_NUMBER><if(CHAPTER_TITLE)>: <CHAPTER_TITLE><endif> - <DURATION>`

**Comment by Hardito** [comment]
@Hardito, unfortunately the chapter name does not work yet over the AudioBookConverter-4.0.1.properties.
yermak: When will you plan to implement it?
Example: chapter_format=<TITLE>-<CHAPTER_TITLE>-<if(BOOK_NUMBER)> Book <BOOK_NUMBER>. <endif>Chapter <CHAPTER_NUMBER><if(CHAPTER_TITLE)>\: <CHAPTER_TITLE><endif> - <DURATION>
--> Kapitel ITunes: -- 0:01:14

**Comment by Kazaa3** [comment]
Thanks @yermak for this amazing piece of software. I've used it a lot in the last days to fill my Ipod Classic with converted mp3/alac/flac audiobooks. First of all I would like to emphasize that I like the naming of the chapters with the time of chapter duration. 

1. What I don't like is the lack of possibility to adjust the naming string. For example, I would like to remove "Book 1'' for some .m1b files that consist of only one book (only: Chapter 1 - 01:23:45). 
 
2. Naming by filename (01 abc) or ID3/APE-Tags like title would be also amazing. 
For Example (filename 01:23:45), or: (track title duration). 
And the ability to save them as templates.

3. Also the option for splitting mp3 files without chapters in variable intervals of certain length (e.g. 10 min pieces) with seperated chapters (Interval 1 - 00:10:00, Interval 2 - 00:20:00, ...). 

4. The optimum would be, if its possible to edit the menus/chapter for already created m1b files by drag and drop them into AudioBookCoverter.

**Comment by yermak** [comment]
1. There is basic configuration of chapter naming configuration via property file - see above, but i will need to review the concept. It seem to be important topic for many users.
2. That's not that strightforward as sometimes chapters consists from multiple files see my demo video how to use version 4.0. However adding duration to chapter name - is not bad idea, even a lot of players do this by themselves.
3. I had this idea in the past as well split by file size (which is kind of the same with constant bitrate), not sure how to make interface consistent and not confusing (I'm trying to keep interface as simple as possible) - any ideas how it should look are more then welcome.
4. That's interesting, it's connected with idea to manually edit all chapter names in "Chapters mode", once this implemented then it should not be an issue (as there is already re-encoding mode for AAC files) - i will definitely do manual chapters edit at some point.

Thank you very much for feedback. I will add those things into backlog.  Currently working on quite annoying issue #21, which requires some fundumental changes and hopefully will be released in 4.1

**Comment by Kazaa3** [comment]
Good to know their is a possibility for chapter naming via property file. A GUI solution would be more accessible, of course. 

Automatically file splitting would be indeed amazing. I had the problem that some created files were too large. They were loaded into the ITunes library, but could not be copied to the Ipod (maybe they exceeded the m4b file format limit for a single file). Splitting them into several parts would be perfect here. Especially if this could happen automatically, maybe with adjustable part size. 

Here is a screenshot of how "Chapters and Verses"" solve the Chapter naming situation. On the right side you can also see the interval splitting functionality. This could be extended with  the splitting functionality. For example a checkbox with listbox: "Split in seperate m4b files" every "1GiB".

![man](https://user-images.githubusercontent.com/43350149/75033135-83c32800-54aa-11ea-8ea8-f4f76f0cc69e.PNG)

But Chapter and Verse has other annoying behaviors where an error message will appear for large files and the file creation process will stop even when the file can be played on most devices (even Ipods). Also the .acc conversion no longer works. Its a freeware but not open source and there has never been an update that fixes these problems for over 5 years. AudioBookConverter could be the successful substitute for this.

**Comment by yermak** [comment]
Ha-ha. Chapter and Verse stopped working for me several years ago. Not sure what the issue - don't start any more in my PCs, which triggered AudioBookConverter birth :)
As for splitting - you still could do this manually - break the book into several parts, by splitting the book in chapters mode, or even tick split box and each chapter will be saved as a separate part, all of them are displayed as single book (i can't test it any more - my 12-years old ipod classic was stolen). I don't think there is a limitation with m4b files, it's more to do with legacy ipods (this issue was highlighed in original version of AudioBookConverted) which I reverse-engineered.
I'm not a UI-expert, but I found Chapter and Verse interface quite diffucult to deal with (that's why chapter config was moved from UI), thus rare users could tweak it. 

What i agree with - chapters names should editable and ideally configurable with some smart suggestions.

**Comment by Kazaa3** [comment]
Can u maybe show how chapter config works? I would like to use the filename shown as Chapter name string.

**Comment by siteuser42** [comment]
Also trying to figure this out, I have some plays that I would like to retain the information in chapter name (Act I, Scene II etc.)

**Comment by yermak** [comment]
@Kazaa3, filenames currently won't be available to be used in chapters naming.
@siteuser42, not sure what do you mean by retaining informaiton? if it's in mp3 tag, it won't be retained in current implementation.

@All, chapter naming will be my next priority, except bug fixing.

**Comment by siteuser42** [comment]
Ah sorry, I was also referring to filename information or also title tag. Thanks for the program.

**Comment by yermak** [comment]
@ALL,
I added a screen to edit chapter title, this allows to include different attirbutes into chapter title including information from mp3 tags.
There is an option to propogate this setting for all chapter in the book or edit each chapter manually.

To edit the chapter title switch to chapter mode, select chapter and press edit button.

![image](https://user-images.githubusercontent.com/380491/77853885-9124ae00-71de-11ea-8727-573a32016f82.png)

If you need to change order of fields or formatting (spaces, dots, semicolums) - you need to go to property file and customise it, but i believe default configuration should work for most of the user. 
This property will be created after first use.

> `<if(BOOK_NUMBER)><BOOK_NUMBER>. <endif>`
> `<if(BOOK_TITLE)><BOOK_TITLE>. <endif>`
> `<if(CHAPTER_TEXT)><CHAPTER_TEXT> <endif>`
> `<if(CHAPTER_NUMBER)><CHAPTER_NUMBER>. <endif>`
> `<if(TAG)><TAG> <endif>`
> `<if(CUSTOM_TITLE)><CUSTOM_TITLE> <endif>`
> `<if(DURATION)> - <DURATION><endif>`

This issue will be closed, please create new ones if there are bugs or ideas how to improve.

**Comment by Kazaa3** [comment]
Hey yermak, amazing update. Thank you.

**Comment by yermak** [comment]
Note there is a minor UI issue - when you selected book title or book number and THEN update them in book info, correct values will be used during encoding, but UI may not refresh instantly to reflect it, but once you do something with chapter tree it will refresh it.

**Comment by Kazaa3** [comment]
> If you need to change order of fields or formatting (spaces, dots, semicolums) - you need to go to property file and customise it, but i believe default configuration should work for most of the user.
> This property will be created after first use.
> 
> > `<if(BOOK_NUMBER)><BOOK_NUMBER>. <endif>`
> > `<if(BOOK_TITLE)><BOOK_TITLE>. <endif>`
> > `<if(CHAPTER_TEXT)><CHAPTER_TEXT> <endif>`
> > `<if(CHAPTER_NUMBER)><CHAPTER_NUMBER>. <endif>`
> > `<if(TAG)><TAG> <endif>`
> > `<if(CUSTOM_TITLE)><CUSTOM_TITLE> <endif>`
> > `<if(DURATION)> - <DURATION><endif>`

Where is this properity file located?

**Comment by yermak** [comment]
> Where is this properity file located?

C:\Users\USER_NAME\Application Data\AudioBookConverter-VERSION

**Comment by Kazaa3** [comment]
> 
> 
> > Where is this properity file located?
> 
> C:\Users\USER_NAME\Application Data\AudioBookConverter-VERSION

For 5.0.0:
C:\Users\USER_NAME\AppData\Roaming\AudioBookConverter-5.0.0\AudioBookConverter-5.0.0.properties

**Comment by Juliana1989** [comment]
i have an importnt question. i want to qut the first part of my MP3 Tag (f.e. "001 Title" shall become "Title" as chapter text.) I tried already to experiment with <rest(Attr)> - maybe somebody can help? that would be very cool for chapter customization. thank you very much. @ @
