### ISSUE TITLE
Error when merging 1 chapter

### ISSUE THREAD

**Issue by UltimateDynamus** [yermak/AudioBookConverter#267]
I'm trying to turn one 1 mp3 file (no built in chapters) into a m4b format. However, when I convert it and it says merging chapters 1/1, right after the bar fills it says error. I've converted about 30 mp3 files last month with no problem but yesterday I had my first error. I always import the mp3, name the title, book number, and import an image for the cover. Then I convert that mp3 as 1 individual m4b. I don't mess around with chapters but it always says merging chapters 1/1. Like I said, I've never had this problem untill yesterday and I know it's not the mp3 file because I tried files I had previously converted to m4b and I get the same error now. Can anyone help me?

**Comment by yermak** [comment]
Please try to remove config file located in C:\Users\%USERNAME%\Application Data\AudioBookConverter-x.y.z.

It might be helpful to post it content here, so, I could try to guess what went wrong

**Comment by yermak** [comment]
i assume not an issue any more, so closing it
