### ISSUE TITLE
chapter combine error

### ISSUE THREAD

**Issue by red-ochre** [yermak/AudioBookConverter#268]
If I load 3 m4a files (**a**, **b**, **c**) and then combine files **b** and **c** to have just 2 chapters and then click start  to create m4b, all works as expected. ch 1 is file **a** and ch 2 is files **b**&**c**.

If I load 4 m4a files (**a**, **b**, **c**, **d**) and then combine files **b** and **c** to have 3 chapters and then click start to create m4b, it ends with **error**. I was hoping to get ch 1 is file **a**, ch 2 is files **b**&**c**, ch 3 is file **d**.

I have log file output if needed.

**(EDIT) I thought that the first situation worked successfully but now I can't recreate it. So both of the above situations produce the error.**

**Comment by yermak** [comment]
@red-ochre 
I tried to reproduce on the latest version
converted 4 mp3 to m4a using split by chapter, then in second round tried to combine **b** and **c** using split by chapter to have 3 output files, and worked as expected, i tried different cominations of merge and it still worked.

If you still experience this issue, i would recommend to share those files with cloud storage and send me a link to **myname**  @ gmail. com explaining how you did this and which version you have used - i will try to reproduce and fix

**Comment by yermak** [comment]
@red-ochre 
Tried to reproduce it again. It all worked, so i will close the issue
