### ISSUE TITLE
Sub-tracks clear chapters list

### ISSUE THREAD

**Issue by jansendotsh** [yermak/AudioBookConverter#269]
When attempting to add chapters to a single file, I try to right-click on the file and create sub-tracks. When I toggle the "Automatically create chapters" option, the chapters list just empties out and I can't complete conversion. There doesn't appear to be anything in the logs, only showing FFMediaLoader.

It seems like this should add chapters under the "Part" so that I can create a chaptered m4b file. Is my understanding of this incorrect or is there potentially a bug here with the sub-tracks feature?

**Comment by yermak** [comment]
Sub-tracks has a bug, I was able to reproduce. Need to be investigated.

**Comment by Protektor-Desura** [comment]
I'm having the same exact problem.

**Comment by yermak** [comment]
This only happens when only one file added and selected option to create chapters for each track.
If more files added - program does work. As a workaround - you could add 2 files (1 temporary) create sub-tracks for first file and remove second file.
I will try to fix it in nearest future
