### ISSUE TITLE
Options to choose file naming scheme

### ISSUE THREAD

**Issue by aterriblegamer** [yermak/AudioBookConverter#27]
I would love to see an options dialog to set my own naming scheme for when I save the file. I have to change it from the default each time now.

**Comment by yermak** [comment]
Hi, could you please elaborate this a bit.
Do you mean you don't want some of the book attributes to be added by default?
E.g. keep just a book name and narrator but skip series and author? And other combinations?

**Comment by yermak** [comment]
> SO for my I upload all my books to Plex. I just want to name the book Author - Title. In some occasions Ill add Series and Series #. Just having a preferences dialog that would allow me to set my preferred naming format from the metadata would be a nice inclusion. thanks so much. This program is awesome and runs so fast on my 16 Core Threadripper.

I will have a look how easy it will be make it configurable, as currently name suggestion works based on filled tags, thus if you fill only author and title an will give you exactly what you are looking for, but you will have no data in tags.
This is definetely not bad idea - i will work on it.

**Comment by yermak** [comment]
@aterriblegamer, I implemented configuration, thus if you want to customize the filename suggestion - it's possible via config - should help you with you plex naming issue.
I don't think adding this via UI makes sense. I would consider several default profiles or schemas - but I don't want to overcomplicate the program w/o clear vision how it will be used.
Please let me know you thoughs.

**Comment by aterriblegamer** [comment]
Got a chance to test this out and it works great. One small bug is that leading zeros get truncated off the series number. Otherwise this does exactly what I was looking for thank you!

**Comment by yermak** [comment]
I'm glad it worked for you. As for leading zeroes - i keep series number as Number, so no way they could be kept, however, this potentially could fixed at formatting level. Don't promise quick fix, but i will have a look
