### ISSUE TITLE
Space in username - error when merging chapters

### ISSUE THREAD

**Issue by ArcusVonSinus** [yermak/AudioBookConverter#270]
I foolishly put a space in my username (so I have folder "C:\Users\Something with spaces\..."). And because of it I have a problem with merging chapters, when the merging starts I get "Error" in the status bar, no file created. From the log: `C:\Users\Something: No such file or directory`
When I created a new user without spaces it worked without a problem.

OS: Win 10 (fully updated)
Version: 5.5.18

**Comment by yermak** [comment]
@ArcusVonSinus 
Please test version 5.6.2 and tell me if issue is still there.

**Comment by Hexaphim** [comment]
I still have this issue in 6.1.2. I tried a portable installation to see if it would perhaps not use %appdata% for this, but no luck.

**Comment by yermak** [comment]
Setting are no longer stored in %appdata% from version 6.2.6. So, issue should not be relevant any more
