### ISSUE TITLE
Unknown Error Before Conversion

### ISSUE THREAD

**Issue by EarthBoundX5** [yermak/AudioBookConverter#272]
I'm running 2x Windows Server 2019 VMs, both should be FAIRLY similar.  One of them works perfectly fine, while the other is presenting an "Error!" immediately upon conversion of the exact same files.

`06-08-2021 00:37:04 INFO  ConverterApplication:382 - Initialising application
06-08-2021 00:37:07 INFO  FFMediaLoader:382 - Loading media info
06-08-2021 00:37:07 INFO  RunProcessFunction:386 - app/external/ffprobe.exe -version
06-08-2021 00:37:08 INFO  RunProcessFunction:386 - app/external/ffprobe.exe -v quiet -print_format json -show_error -show_format -show_streams -show_chapters P:\Audio\Audio Books\Dan Brown\The DaVinci Code\Audio Book - Dan Brown - The DaVinci Code 1.mp3
06-08-2021 00:37:08 INFO  FFMediaLoader:386 - Created AudioBookInfo AudioBookInfo[title=, writer=, narrator=, series=, genre=, year=, bookNumber=0, totalTracks=0, comment=, tracks=[]]
06-08-2021 00:37:08 INFO  RunProcessFunction:386 - app/external/ffprobe.exe -v quiet -print_format json -show_error -show_format -show_streams -show_chapters P:\Audio\Audio Books\Dan Brown\The DaVinci Code\Audio Book - Dan Brown - The DaVinci Code 2.mp3
06-08-2021 00:37:08 INFO  FFMediaLoader:386 - Created AudioBookInfo AudioBookInfo[title=, writer=, narrator=, series=, genre=, year=, bookNumber=0, totalTracks=0, comment=, tracks=[]]
06-08-2021 00:37:08 INFO  RunProcessFunction:386 - app/external/ffprobe.exe -v quiet -print_format json -show_error -show_format -show_streams -show_chapters P:\Audio\Audio Books\Dan Brown\The DaVinci Code\Audio Book - Dan Brown - The DaVinci Code 3.mp3
06-08-2021 00:37:08 INFO  FFMediaLoader:386 - Created AudioBookInfo AudioBookInfo[title=, writer=, narrator=, series=, genre=, year=, bookNumber=0, totalTracks=0, comment=, tracks=[]]
06-08-2021 00:37:08 INFO  RunProcessFunction:386 - app/external/ffprobe.exe -v quiet -print_format json -show_error -show_format -show_streams -show_chapters P:\Audio\Audio Books\Dan Brown\The DaVinci Code\Audio Book - Dan Brown - The DaVinci Code 4.mp3
06-08-2021 00:37:08 INFO  FFMediaLoader:386 - Created AudioBookInfo AudioBookInfo[title=, writer=, narrator=, series=, genre=, year=, bookNumber=0, totalTracks=0, comment=, tracks=[]]
06-08-2021 00:37:08 INFO  RunProcessFunction:386 - app/external/ffprobe.exe -v quiet -print_format json -show_error -show_format -show_streams -show_chapters P:\Audio\Audio Books\Dan Brown\The DaVinci Code\Audio Book - Dan Brown - The DaVinci Code 5.mp3
06-08-2021 00:37:09 INFO  FFMediaLoader:386 - Created AudioBookInfo AudioBookInfo[title=, writer=, narrator=, series=, genre=, year=, bookNumber=0, totalTracks=0, comment=, tracks=[]]
06-08-2021 00:37:42 ERROR FFMpegConcatenator:386 - Concat Error: ffmpeg version 4.3.1-2021-01-01-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-shared --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
C:\Users\ADMINI~1\AppData\Local\Temp\1\filelist.1627111891503.txt: Invalid data found when processing input

06-08-2021 00:37:42 ERROR FFMpegConcatenator:382 - Error during concatination of files:
uk.yermak.audiobookconverter.ConversionException: Concatenation exit code 1!=0
	at uk.yermak.audiobookconverter.FFMpegConcatenator.concat(FFMpegConcatenator.java:74)
	at uk.yermak.audiobookconverter.ConversionJob.run(ConversionJob.java:84)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Error: ffmpeg version 4.3.1-2021-01-01-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-shared --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
C:\Users\ADMINI~1\AppData\Local\Temp\1\filelist.1627111891503.txt: Invalid data found when processing input

	... 5 more
06-08-2021 00:37:42 ERROR ConversionJob:382 - Error during parallel conversion
java.lang.RuntimeException: uk.yermak.audiobookconverter.ConversionException: Concatenation exit code 1!=0
	at uk.yermak.audiobookconverter.FFMpegConcatenator.concat(FFMpegConcatenator.java:82)
	at uk.yermak.audiobookconverter.ConversionJob.run(ConversionJob.java:84)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: uk.yermak.audiobookconverter.ConversionException: Concatenation exit code 1!=0
	at uk.yermak.audiobookconverter.FFMpegConcatenator.concat(FFMpegConcatenator.java:74)
	... 4 more
Caused by: java.lang.Error: ffmpeg version 4.3.1-2021-01-01-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-shared --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
C:\Users\ADMINI~1\AppData\Local\Temp\1\filelist.1627111891503.txt: Invalid data found when processing input

	... 5 more
06-08-2021 00:37:47 INFO  ConverterApplication:382 - Closing application
`

**Comment by yermak** [comment]
Most likely duplicates #347
