### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by pixelsophie** [yermak/AudioBookConverter#28]
Thanks for these Software help me verry much! Do you would implement in future a Option for Chapter Description or Something else? Little bit more options for creat a book (not only ripp it for iTunes)? thanks a lot it works nice.

**Comment by jayrodathome** [comment]
Thanks from me also. This software saved the day. I haven't been able to find it's equal on Windows 10.

**Comment by yermak** [comment]
> Thanks for these Software help me verry much! Do you would implement in future a Option for Chapter Description or Something else? Little bit more options for creat a book (not only ripp it for iTunes)? thanks a lot it works nice.

pixelsophie, i'm really glad someone is using this tool:) 

I had an idea of more advanced chapter management - i.e. combining several mp3 files into single chapter, but this will make interface more clumsy.
As for description for chapters - i'm not sure if it's possible - as iTunes shows only Description for the book - that's could be done if someone needs it.
If you have other ideas please feel free to raise them as separate tickets - I will try to too look at them when have some spare time.

**Comment by yermak** [comment]
@pixelsophie, I implement more advanced chapter management in version 4.0.
Added some video to show how it works https://www.youtube.com/watch?v=N7JrujMfids
Please create new issue if it's not something you are looking for.
