### ISSUE TITLE
Windows Smart Screen Protection

### ISSUE THREAD

**Issue by jayrodathome** [yermak/AudioBookConverter#29]
Windows (dumb) Screen protection pops up when installing this software. Not sure if it's from the recent windows update or if it's always done that. Have to click more info to allow the installation. I know this used to happen with a few other programs I had but the developer did something and it no longer happened. Just pointing it out in case you are aware or anyone comes here the software is safe and it's great so don't hesitate installing it!

**Comment by yermak** [comment]
I think it's more related to installation binary downladed from internet.

**Comment by yermak** [comment]
There is nothing I am going to do fix it, probably digital signature could help, but this is not priority.
