### ISSUE TITLE
temp files aren't removed

### ISSUE THREAD

**Issue by Soopx** [yermak/AudioBookConverter#307]
whenever I use this application, it eats all my diskspace until nothing is left.  I thought I was clearing it with a reboot, but there's definitely something permanently occupying space too.

In leui of a fix, can you tell me the folder this app uses as a temp directory?  I really need to recover space asap

**Comment by Soopx** [comment]
I found the folder, C:\Users\user\AppData\Local\Temp

there were a few other programs responsible, but this should clear without needing a reboot

**Comment by jeff47** [comment]
Agreed.  Mine starts failing because I use a ram disk as a tmpfs, and it fills it up completely.  Needs to be fixed.

**Comment by yermak** [comment]
this will be fixed in next release. Implemented (needs to be tested)

**Comment by yermak** [comment]
Fixed
