### ISSUE TITLE
Settings or documentation update

### ISSUE THREAD

**Issue by JNatael** [yermak/AudioBookConverter#31]
The documentation seems to mention multiple file formats possible for mp3 files, as noted here:

> Convert Audiobook from mp3 to m4b.
> Convert mp3 to Audiobook.
> Convert mp3 to ipod format.

In the app however I seem to be only able to convert to m4b format. In my case that doesn't help as the device I use unfortunately can't read m4b; I'd hoped to be able to use this to generate .ogg files in particular, as they can still use chapters.

So is there a setting to switch to other formats as output? Or, alternatively, maybe the documentation should be updated to make this clearer?

**Comment by yermak** [comment]
JNatael,
Thank you for your comment. I made slight changes to documentation.
Original idea was to provide audiobook for Apple devices, as for other platforms mp3 is not an issue.
I will have a look into this in the future, i'm not sure which players can support this format to perform testing.

**Comment by yermak** [comment]
@JNatael,
Could you please advise which codec your device suports? vorbis or opus?

**Comment by yermak** [comment]
@JNatael, ogg support is added in version 4.6.0
