### ISSUE TITLE
macOS 12.0.1 Application is damaged and can't be opened

### ISSUE THREAD

**Issue by gh0sti** [yermak/AudioBookConverter#313]
I just downloaded your latest version and tried running it on my 2019 16in macbook pro on latest macos and the app won't launch. Says app is damaged and I have to delete it. I tried even opening in with right click open option and still wouldn't let me run it.

**Comment by yermak** [comment]
Hi @gh0sti,
you could try to follow instruction here https://github.com/yermak/AudioBookConverter/wiki/Installation

Or just purchase MacOs version here https://store.steampowered.com/app/1529240/AudioBookConverter/

**Comment by yermak** [comment]
Duplicates #173

**Comment by dmuiX** [comment]
Not possible to use it on Mac OS 12. Same error exists and the instructions are not working.

**Comment by yermak** [comment]
Duplicates #580
