### ISSUE TITLE
"ConverterApplication.app" is damaged and can't be opened

### ISSUE THREAD

**Issue by hijakz** [yermak/AudioBookConverter#319]
After running the 5.5.26 DMG and copying the app to Applications folder, I then attempt to open the ConverterApplication.app . But I get this error message: 

"ConverterApplication.app" is damaged and can't be opened. You should move it to the bin.

Tested today on M1 MacOS 12.0.1

**Comment by yermak** [comment]
1) i don't think it will work on M1
2) https://github.com/yermak/AudioBookConverter/wiki/Installation
3) You can buy singed MacOS build from [Steam](https://store.steampowered.com/app/1529240/AudioBookConverter/) (IMPORTANT: Tested on x64 - I have no idea if it will work on M1).

**Comment by yermak** [comment]
Duplicates #313

**Comment by yermak** [comment]
Duplicates #173

**Comment by yermak** [comment]
Duplicates #580
