### ISSUE TITLE
Strange (chinese?) characters shown in audiobook apps

### ISSUE THREAD

**Issue by Cassock** [yermak/AudioBookConverter#32]
For some reason, metadata for one particular audiobook I have shows fine in my player apps when I add as mp3s (Voice, Smart Audiobook player, etc.), but after converting to m4b, it shows strange characters for the author and title: https://imgur.com/rQJSVcp

When reading the metadata in Windows or Calibre or any number of other media tagging apps, they all show the correct (English) info.

Is this a UTF encoding issue?

**Comment by yermak** [comment]
@Cassock, it seem like issue with your player.
I always use non-latin characters and never experienced this.

**Comment by Cassock** [comment]
I strongly doubt it's an issue with several distinct audiobook players all having the same exact error, but thanks for the response anyway. If you'd like to take a look at the source and converted files, let me know and I can send them.

**Comment by yermak** [comment]
Cassock, please send a link to sources files to my_account_name @ gmail.com.
I will try to reproduce.
