### ISSUE TITLE
Encoding does not start...

### ISSUE THREAD

**Issue by yermak** [yermak/AudioBookConverter#347]
**Unreliable configuration storage causes application to stop working**

There are multiple bug reports about app not starting, as there are not many logs provided it's difficult to diagnose to root cause.
However, typically removing configuration helps, so need to change the way settings are stored to make it more robust

**Comment by yermak** [comment]
Should be fixed in version 6+ where architecture of setting was reworked.

**Comment by Dr-Ari-Gami** [comment]
Hi there, I have this same issue. When I click start, nothing happens. 

Here is a screenshot of my configuration (with my username censored): https://i.imgur.com/Yng5yhr.png

I couldn't find any logs, does anyone know what is causing this?

Thanks!
