### ISSUE TITLE
Feature Request: Artwork  Functionality

### ISSUE THREAD

**Issue by g4dget** [yermak/AudioBookConverter#36]
Thanks for making this great program. I have a couple suggestions / feature requests for the Artwork tab:
1. Show the resolution of selected images
2. Allow pasting of images from the clipboard as an alternative method for adding artwork

**Comment by yermak** [comment]
g4dget, thank you for suggestion.
Those are very useful ideas.

**Comment by yermak** [comment]
1. Resolution is shown as tooltip for images
2. Added pasting images from clipboard:
 - pasting image files copied from explorer (no dran-n-drop for now)
 - pasting raster images (printscreens and copy image browser)
 - pasing vector images (should you create quick cover in PowerPoint)
