### ISSUE TITLE
Does not install on macOS Monterey

### ISSUE THREAD

**Issue by WoodpeckerBaby** [yermak/AudioBookConverter#365]
> Open termainal use exactly `cd /Application/ConverterApplication` `./Contents/MacOS/ConverterApplication`

This is not what the app is called, but even when I manually fixed it, it didn't open though Terminal. 

It's under `/Applications/AudiobookConverter.app/Contents/MacOS/AudiobookConverter`

Right click then open also didn't work. 

<img width="274" alt="Screen Shot 2022-01-05 at 12 15 12 AM" src="https://user-images.githubusercontent.com/14303318/148089596-a9ed90b2-ef19-4db3-ac04-d042e54af168.png">

Is it possible to make it available through HomeBrew?

**Comment by yermak** [comment]
I have not test on Monterey, just updated yesterday.

However, proper Mac version requires apple developer licence to sign the app. So, signed mac version is and will be available from steam only https://store.steampowered.com/app/1529240/AudiobookConverter/

**Comment by tamaracks** [comment]
> I have not test on Monterey, just updated yesterday.
> 
> However, proper Mac version requires apple developer licence to sign the app. So, signed mac version is and will be available from steam only https://store.steampowered.com/app/1529240/AudiobookConverter/

What can one do if one can't install Steam?

I don't know what's going on, but the Steam client is not installing on my M1 MacBook. I downloaded it, but it seems the download is basically a stub, and upon launch it immediately starts an update. Except that it makes no progress on updating and just sits there forever.

So I'm stuck. I can't install Steam, and I can't install it from the GitHub download.

**Comment by WoodpeckerBaby** [comment]
I don't even know what steam is. It's either homebrew or Apple Store. Pretty weird. I found a few different apps that work perfectly and intuitively. Search App Store for 'Audiobook Binder', it's simple, beautiful and free.

**Comment by yermak** [comment]
@WoodpeckerBaby, thank you very much for your opinion. This is not a place to advertise other products :)
Please feel free to use Audiobook Binder if you are happy with its features and performance.
This product is opensource, however apple digital signature is not free which is required to run any application on Mac OS. Eventually I will add this application to AppStore.

**Comment by yermak** [comment]
> What can one do if one can't install Steam?
> 
> I don't know what's going on, but the Steam client is not installing on my M1 MacBook. I downloaded it, but it seems the download is basically a stub, and upon launch it immediately starts an update. Except that it makes no progress on updating and just sits there forever.
> 
> So I'm stuck. I can't install Steam, and I can't install it from the GitHub download.

@tamaracks, this application does not work on M1 MacBooks and I don't have plans in near future to build it for M1. This will require too much work and user base is not big enough yet.

**Comment by WoodpeckerBaby** [comment]
You can distribute an unsigned app for macOS free of charge. Only right clicking then hit open is required, for the first run. I have installed countless unsigned apps without problems. 

Your app is just broken.

**Comment by tamaracks** [comment]
> @tamaracks, this application does not work on M1 MacBooks and I don't have plans in near future to build it for M1. This will require too much work and user base is not big enough yet.

Ah well. Good to know, but sad.

**Comment by yermak** [comment]
@WoodpeckerBaby,
You were right - there was minor issue which has broken the build. New version 6.0.1 should work now.

**Comment by yermak** [comment]
> > @tamaracks, this application does not work on M1 MacBooks and I don't have plans in near future to build it for M1. This will require too much work and user base is not big enough yet.
> 
> Ah well. Good to know, but sad.

I'm really sorry about that, Apple did not make life easier with new M1 Chip, all components need to be rebuilt. My application is platform independent, but there are some dependencies which will require solid efforts and I don't have such hardware yet.
