### ISSUE TITLE
[Feature Request] Dark Mode

### ISSUE THREAD

**Issue by stayxnegative** [yermak/AudioBookConverter#366]
It'd be nice to get a dark mode UI support, because the current UI is rather blinding.

**Comment by yermak** [comment]
Thanks, this should be easy will add this into next release.
Note to myself: 
`root.setStyle("-fx-base: rgba(60, 60, 60, 255);");`

**Comment by yermak** [comment]
Dark mode support is added, will be available via settings in next release
