### ISSUE TITLE
Extra spaces in suggested filename...

### ISSUE THREAD

**Issue by Snille** [yermak/AudioBookConverter#370]
Hi, thank you for this great program! I'm currently converting all my "CD-Books" to one file-m4b-books...
I noticed that there are one "extra" space (making it two spaces) between the "Author" and  "[Series]" and the same phenomenon between "[Series]" and "Book name"....
Example: "Dan Brown`  `- [Robert Langdon - 01]`  `- Angels & Demons (Richard Poe).m4b"
Hopefully it's a simple fix. :)

Thank you!

**Comment by yermak** [comment]
@Snille , thank you for feedback and raising the issue.
I have seen this bug, but as it is minor - did not fix it earlier.
As there is template used for filename suggestion it might be slightly more tricky to fix it, but possible. I will have a look when will be moving naming templates to editable settings.

**Comment by yermak** [comment]
Fixed and will be released in next version, also most likely to be customisable in next version
