### ISSUE TITLE
[Improvement] Finer control over VBR

### ISSUE THREAD

**Issue by deltz025** [yermak/AudioBookConverter#373]
This app has been one of my absolute favorite finds for the last year or so, and I've been using it to convert all my old MP3 folders and M4B audiobooks into nice, small Opus files. Unfortunately, the VBR slider seems to be a bit too ambitious for conversion - when set to 1, the files are compressed with some loss in audio quality, but at 2, the output file is almost always larger in size than the input. 

Would it be possible to have more granular control over VBR quality? I'd like to match the quality of the original input files, while reaping the benefits of Opus' stellar compression. 

Thanks for your hard work!

**Comment by yermak** [comment]
I will have a look.

**Comment by yermak** [comment]
It will be improved in next release, however, there will be no true correct solution.
For the record:
opus supports 3 type of bitrate control: hard-cbr, vbr (with target bitrate), constraint vbr (cvbr). AudiobookConverter supports only first 2. and similar to quality settings in other encoders where we pass "magic number" w/o real understanding of its impact, we pass "target bitrate", however, it's more like a hint rather then real limit (unlike 3rd option). 

So, AudibookConverter will treat settings from 1 to 5 as 8, 16, 32, 64, 128kbps per channel. Starting from versions after 6.0.1. If as a result of experiments some one could advise better hints for target bitrates in vbr mode - i will be ready to include those into the program
