### ISSUE TITLE
"Year" tag missing for imported m4b-Files

### ISSUE THREAD

**Issue by Kazaa3** [yermak/AudioBookConverter#383]
For .m4a and .m4b files (e.g. from iTunes) the meta information of the release year ("YEAR" or "Recorded date") is not taken over and remains empty.

**Comment by yermak** [comment]
It should be fixed now and will be released in next version.
I will review all tags compatibility soon to make tags parsing more robust

**Comment by yermak** [comment]
iTunes actually stores it's in tag "date" in format "2022-06-05T19:09:25Z", which is not actually Year :) 
However, I will pickup year from it.
Also i noticed that iTunes (now?) stores track_number in just tag "track", so it will be supported from next version as well.

@Kazaa3, thank you again and again for reporting!
