### ISSUE TITLE
Flatpak version for linux?

### ISSUE THREAD

**Issue by Gitraffe** [yermak/AudioBookConverter#388]
Hi,

How hard would it be to make flatpak release for linux? As far as I understand it would support all distros with same package. 
So no need to build from source with arch etc. baces systems. :)

**Comment by yermak** [comment]
It's definitely not bad idea, but share of Linux users is about 2.5%. So, not sure it worse it - investing my time into learning Flatpack, especially i'm not quite sure it's better then Snap (I actually looked into it before, but understood it will require a lot of efforts with unclear benefit for end-user.
There is static build available which does the job.

If someone can provide patch for Flatpack or Snap, i will be happy to test it.

But thanks for the idea.

**Comment by trymeouteh** [comment]
Flatpaks are better than Snap and is having much more adoption. Either Flatpak or AppImage would be the best way to release the app on Linux.
