### ISSUE TITLE
minor spelling error: "then" on quality

### ISSUE THREAD

**Issue by eturk1** [yermak/AudioBookConverter#389]
on quality, it should be "than" which is for comparison of size as in "greater than" (>)
<img width="331" alt="image" src="https://user-images.githubusercontent.com/525280/165865076-0178e7c5-3f19-4ff2-9a4b-4670c878e481.png">

"then" is used with time or something happening after, as in: do this then that

**Comment by yermak** [comment]
Fixed. Will be released in next version
