### ISSUE TITLE
Genre drop down box

### ISSUE THREAD

**Issue by HenryMontrose** [yermak/AudioBookConverter#39]
Why is it necessary to have a drop down box, when it never remembers anything, think it is unnecessary unless you are going to make it work..
How do I make the constant bitrate, stay as previous, it always seems to revert back to 128 which is far too high for an audiobook

**Comment by yermak** [comment]
@HenryMontrose,
Thanks for reporting. Dropbox is fixed now and will be released in next patch version.
For constant bitrate, just don't use auto option, manual selection does work.
I probably have to remove auto  (and just stick with default manual settings - as it's confusing see similar request #34)
