### ISSUE TITLE
Problem with Book series in filename

### ISSUE THREAD

**Issue by andrewwigmore67** [yermak/AudioBookConverter#41]
Hey yermak, love the program, but there's still a problem with the filenames when you have a Book series.

Firstly, there's an extra "]" in the template, it should be:

<WRITER> <if(SERIES)>- [<SERIES><if(BOOK_NUMBER)> -<BOOK_NUMBER><endif>] <endif>- <TITLE><if(NARRATOR)> (<NARRATOR>)<endif>

Secondly, SERIES doesn't return the Series, it returns the Title (AudioBookInfo.java?)

**Comment by yermak** [comment]
Hi,
This one is already fixed sometime ago see commit
https://github.com/yermak/AudioBookConverter/commit/a0cca374bcb09dbbf83c74b782c61e887873b306

And Series/titles was fixed as well, see commmit https://github.com/yermak/AudioBookConverter/commit/7d10d9dc9e7636a481caffb499eede96b886b183

I will release fix shortly, was going on another issue and was going to release all fixes togehter, but probably do it sooner.

**Comment by yermak** [comment]
Fixed in version 4.2.2
