### ISSUE TITLE
file extensions 

### ISSUE THREAD

**Issue by andrewwigmore67** [yermak/AudioBookConverter#42]
Thee program doesnt seem recognise files with an extention of ".MP3" in capital letters. ".mp3" works fine though :)

**Comment by yermak** [comment]
@andrewwigmore67, thank you for submitting.
This is bug is just a shame - fixed it in 4.2.2.

**Comment by andrewwigmore67** [comment]
Wow! Fantastic supprt and response! Keep up the good work
