### ISSUE TITLE
Cant start converting anymore

### ISSUE THREAD

**Issue by jabbawocky0815** [yermak/AudioBookConverter#424]
Hi! I have successfully converted several mp3 books to m4b.
But after the 5th book i cant convert anymore.
When i click Start, nothing happens.
Even when i restart AudiobookConverter or restarting Windows (Win10)
I am using the portable version (6.1.0)
Even when i extract the files again from the zip container and start the converter, its always the same.

**Comment by yermak** [comment]
Quick solution: go to your home directory/Application Data/ find AudioBookConverter forlder and delete it.
This should help.

To help me to improve the program please send log file from this folder to my nickname at gmail.com

Thanks.

**Comment by jabbawocky0815** [comment]
Hi! Thanks for the answer.
I figured out that i have to start the app with admin rights. than it works.

**Comment by jeroenwalter** [comment]
I have the same issue with 6.1.1 portable on Win10. 
It converted several books successfully, then I tried to convert one of them again, no luck, Start didn't do anything.
Have deleted the Application Data folder and unzipped the portable version to a new folder, still no luck, Start doesn't do anything. I've tried running it in administrator mode as well. Nothing. Not even a log file.
Any suggestions on how to fix this?

**Comment by jeroenwalter** [comment]
Well, apparently there also was an AudioConverter folder in AppData\Roaming. When I deleted that one, conversion once again worked..... 
I converted some other books, trying to reproduce the bug, but it's still working.
Hoping for the best......

**Comment by vidtech200** [comment]
(New comment)
I had commented below that 6.1.1 was still having the same problem, subsequent to posting in issue 379, I found this open issue, and did the same as jeroenwalter...   deleted the audioconvertor log folder out of my Apps\Roaming.

Similarly I am also now working. (I did save the old log file in case you'd still like it, but here was the gist (not putting whole file in)...

after the last successful conversion I had the following warning and info line, that appears to have been repeated every time I tried the start button on different files/folders.  (was the last of the log, with the exception of the  - Closing Application line, with both being duplicated 8 times which is about how many different times I tried to "start" a conversion)

13-08-2022 23:41:54 WARN  FileDataWriter:195 - Can't open directory channel. Log directory fsync won't be performed.
13-08-2022 23:41:54 INFO  EnvironmentImpl:382 - Exodus environment created: C:\Users\Owner\AppData\Roaming\AudiobookConverter-6.1.1

(Previous comment that I cut out and moved to this thread)
I am experiencing the same problem with Win10 & 6.1.1, nothing will "start" with press of the start button.   It was a directory with a single mp3 file, a que file, and a jpg (cover) file.  Thinking it was just this book, tried the next in the series with no go as well.   My first google read was here on github (Issue #25), so I tried some of the thoughts/fixes from there...
- it was a nested directory, so I copied the mp3 only into a 2 letter directory off of root, with a short file name (in case name string was too long); no-go
- nothing looked out of the ordinary with the file (VLC played it fine), but tried renaming it w/ mp3tag as some had suggested worked; no-go
- then I thought, hey, let's back up to one I'd already converted (was keeping originals on separate drive until conversions were done, and the exact same mp3 I had converted w/ no problem yesterday will also not start, so assuming that yes, something broke the program.

**Comment by nevarDeath** [comment]
Hi, I'm experiencing this using AudioBook Converter 6.1.1 Portable. Deleting the folder in 
`%USERHOME%/AppData/Roaming/AudiobookConverter-6.1.1 `
did allow me to start converting again.

Computer: Surface Pro 3
OS: Windows 10 Pro v21H2 build 19044.1889
Proc: Intel Core i3 1.5Ghz
RAM: 4GB

I've attached my log. I just started using it today.
[AudioBookConverter.log](https://github.com/yermak/AudioBookConverter/files/9502327/AudioBookConverter.log)

**Comment by watercayman** [comment]
Hi Yermak,

First thank you for this excellent product.  Similar info for your bug hunt:

I experienced the same issue as above.  The logs showed the same issues:

`21-12-2022 22:48:11 WARN  FileDataWriter:195 - Can't open directory channel. Log directory fsync won't be performed.
21-12-2022 22:48:11 INFO  EnvironmentImpl:382 - Exodus environment created: C:\Users\water\AppData\Roaming\AudiobookConverter-6.1.2
21-12-2022 22:48:11 WARN  FileDataWriter:195 - Can't open directory channel. Log directory fsync won't be performed.
21-12-2022 22:48:11 INFO  EnvironmentImpl:382 - Exodus environment created: C:\Users\water\AppData\Roaming\AudiobookConverter-6.1.2`

I tried starting in admin mode and no joy.  It seemed to be stuck trying to open a write folder that it didn't have perms to.  But nothing changed in the environment that I can think of.  It just stopped working.

I took the advice above and deleted the directories in the roaming folder (I had three of them for different versions).  This successfully got it working again.

Env: Windows 10 Home, Intel i7, 16GB ram.

**Comment by littleblackdog77** [comment]
I'm having continual problems with 6.1.2. It worked for a few days but now stops after two or three conversions. The above trick works but I have to keep deleting the folder every two to three conversions.

Windows 11, Intel i7, 64GB ram.

**Comment by yermak** [comment]
I believe those bugs are outdated, so, I close the ticket
