### ISSUE TITLE
Version check 6.1.1 portable broken

### ISSUE THREAD

**Issue by jeroenwalter** [yermak/AudioBookConverter#431]
Each time I start the program, it checks the file https://raw.githubusercontent.com/yermak/AudioBookConverter/version/windows.txt
However, that file still reports version 6.1.0.
So the New Version Available dialog keeps popping up for the wrong reason.

I've resorted to set the platform property in app/path.properties from windows to steam, so the version check doesn't trigger, but that's a workaround, not a solution.

Please update the windows.txt file with the latest version.

**Comment by yermak** [comment]
@jeroenwalter 
Thanks for reporting. Fixed now.
