### ISSUE TITLE
feature request: Leading zeros before chapter names

### ISSUE THREAD

**Issue by rahulmb** [yermak/AudioBookConverter#434]
Currently naming starts from Chapter 1, Chapter 2, ...
Several devices read this order as Chapter 1, Chapter 11, Chapter 2, Chapter 21, ...
When adding series together this is a bigger problem as chapters can reach into 100s

If chapters could have an option for 0 padding and the number of 0s this would fix the problem. Eg. Chapter 01, Chapter 02...

**Comment by yermak** [comment]
I believe this is already in place for several version.
If there is a scenario where this happens - not having padding zeros, please provide more details
