### ISSUE TITLE
Incorrect 'New Version Available - Would you like to download new version' message.

### ISSUE THREAD

**Issue by sgmoore** [yermak/AudioBookConverter#446]
This prompt appears every time I start this program.

I am running 6.1.2 and I think the code is comparing against the contents of https://raw.githubusercontent.com/yermak/AudioBookConverter/version/windows.txt which is currently AudiobookConverter-6.1.1 , but it looks as if the logic is simply checking if the versions are different and not taking into account that the version I am running is actually newer.

**Comment by yermak** [comment]
Fixed now. thanks for reminding.
