### ISSUE TITLE
Title/Series initialization problems

### ISSUE THREAD

**Issue by jjones3905** [yermak/AudioBookConverter#447]
This seems related to the (currently) closed issue #437.

When processing, the _Title_ and _Series_ fields get written out fine, it seems to the _Track Title_ and _Album Title_ tags respectively. However, it seems that when opening a file, both Title and Series get initialized from _Album Title_.

I suspect what we're looking for is something along the lines of initializing  _Title_ from the first (or only) _Track Title_ when adding files to an empty file  list.

Thanks.

Edit: Sorry. Using 6.1.2 on Windows

**Comment by yermak** [comment]
@jjones3905 ,
You are right.

Just to explain: when dealing with books from mp3 files, majority of them store book name in Album tag, and keep chapter name or just numbering in Title tag, there are some cases where Album track is empty or store series name and book name together with chapter number are stored in Title tag.
There is no way to understand it without applying some AI for this, which seem to be overkill for the task.

When book is converted I place book name in to Title tage and use album tag to store book series name, which seems to me logial way to keep the information.
However, if you re-open converted book, you lose book name again as Album information is used to populated both fields Title and Series

**Comment by jjones3905** [comment]
Thanks for the update. It is logical, explained like that.

The only way I can think of addressing this on re-opening is to use some
obscure ID3 tag to save a flag that it's been processed already by
Audiobook Converter and thus reads back in using your output conventions.

Probably more of a hack than you want. 😊

Jon
