### ISSUE TITLE
Extracted Art Work

### ISSUE THREAD

**Issue by jjones3905** [yermak/AudioBookConverter#448]
Since the update to 6.1.2, when adding  a chaptered m4b file, named, say, TITLE.m4b, the artwork seems to be extracted to a file TITLE.art[0].png in the same directory as the source file. Shouldn't these be extracted to the temp directory instead?

They are not deleted when closing the program.

Thanks,
Jon

**Comment by yermak** [comment]
Good catch. Thanks. Will fix it in next version.

**Comment by yermak** [comment]
Fixed
