### ISSUE TITLE
Convertion with Errors during splitting by tracks

### ISSUE THREAD

**Issue by SandraMedvedeva** [yermak/AudioBookConverter#457]
I am trying to split an mp3 book into tiny parts in order to listen to the book on mp3-player (where I have only next/previous track buttons and cannot switch back inside one track). That's why I need very small parts of 2-3 mins. But when I try to convert a file into 20-40 small files, 1/3 or even 1/2 of the flows are Error! and I have just some files as a result. It seems that flows cannot be restarted in that case. Could you take a look?

I use AudiobookConverter-6.1.2 on Windows 7.

**Comment by yermak** [comment]
I was able to reproduce the error - investigating...
Just to reconfirm the flow: You add one or several mp3 files, convert to chapters, then go inside chapter and select sub-track on the file, select duration 2 minutes (for each of mp3 files within all chapters) and select split BY CHAPTER, encoding mp3 and a result get an error.

I have quite strange results - some sub-tracks converted and some not, which is really strange that source is single mp3 file, so assume source is ok as well as output paramters (so, must be timing issue...)

**Comment by yermak** [comment]
Fixed. will be released in next version
