### ISSUE TITLE
Parsing of file tags

### ISSUE THREAD

**Issue by Kazaa3** [yermak/AudioBookConverter#46]
The Year and Comment tag is not adopted from the source files. Maybe it would also make sense to use the album tag as title insteed for the series field.

![Missing tag fields](https://user-images.githubusercontent.com/43350149/77908307-8b38d680-728b-11ea-9672-0c21f6c39fba.PNG)

**Comment by yermak** [comment]
@Kazaa3,
thanks for finding - i did not realize that year tag was chaged from "year" to "date" between mp3 tags spec from v1 to v2. Similar story with comments.
I had similar thoughs on "album" tags...

Fixed. Will be released in next bugfix version.

**Comment by yermak** [comment]
Released in 4.4.0
