### ISSUE TITLE
Where are the 018 option "every mp3 as single m4b file or all into one m4b file"

### ISSUE THREAD

**Issue by RoNoLo** [yermak/AudioBookConverter#464]
I purchased the software via steam because I thought the multicore processing will help me very much. I do have very old audio book mp3s which some are a single audio book and sometime a series of numerated mp3s are to be converted into 1 m4b file. 

The old 018 software version had this handy option which did exactly what I want. I miss this function in the modern version.
<img width="298" alt="image" src="https://user-images.githubusercontent.com/17102148/226069389-dc0b478b-7fe3-4cd0-9f1b-22b664bd6f86.png">

Did I miss something or is it just gone?

**Comment by yermak** [comment]
Thank you, very much for purchase.
It keeps me motivated to improve this software further.
I think what you lioking for is called "split by chapters". 
As a result yous should have as many files as you have chapters.
Note: you could be much more flexible, then in verions 0.18. I.e. You could chapters way more flexible...

**Comment by RoNoLo** [comment]
"split by chapters" might be something I look for, but to be honest it is misleading for me, because I do not know every magic markers which might be hidden in a 250MB mp3 file. I find it more simple to select somewhere: every mp3 becomes a m4b and a series of mp3s which I can select and mark are going into a single m4b file.

Anyways good work. I'll experiment with that chapter feature if it really does what the old 018 version did.

**Comment by yermak** [comment]
After opening mp3 file switch to Chatpers mode and if you see that your mp3 containted internal chapter markers, just merge them back into single chapter.
