### ISSUE TITLE
After press on chapterise button nothing appear in window

### ISSUE THREAD

**Issue by maximtsirik** [yermak/AudioBookConverter#466]
On my MacBook Pro M2, after I add audio files and then press on chapterise button list of files disappeared and nothing then happened. Also if i want to start processing without chapters, it doesn’t work. I use Stem version of program. It shows version 6.1.2

**Comment by markbharris** [comment]
Well I am here for the same issues, and I see that you did not get a response, this does not look good for me

**Comment by yermak** [comment]
See #580

**Comment by yermak** [comment]
Beta for Mac OS X is available
https://github.com/yermak/AudioBookConverter/issues/580#issuecomment-2268738667
