### ISSUE TITLE
GUI is too tall to fit on screen.

### ISSUE THREAD

**Issue by BenMcLean** [yermak/AudioBookConverter#467]
I run Windows 10 at 1080p resolution and 150% DPI zoom. But that setting makes this app is too tall to fit on screen.

I think the problem here is the GUI's lack of DPI awareness. Some contextual information for that follows:

On Windows 10, there is a feature called UI Scaling described in this article: https://www.thurrott.com/windows/windows-10/4597/windows-10-feature-focus-display-scaling

This is a good feature for people with vision problems to make the text and GUI elements bigger in most Windows programs.

This feature first started on Windows XP but programmers only started having to worry about it when Windows 7 started trying to scale up apps that didn't tell the newer Windows API that they were DPI-aware. I believe that is what the problem is for this app As InfoWorld says, "For apps that aren't high-DPI aware, Microsoft has a quick and dirty fix called DPI virtualization. Windows deliberately reports the wrong DPI resolution to such apps, so their elements render as if they were on a lower-resolution display. The results are then zoomed to fit the current display." http://www.infoworld.com/article/2952506/microsoft-windows/high-resolution-displays-reveal-windows-10-blind-spot.html

What needs to be done to fix this is to make Windows apps DPI-aware, as discussed in this article from Microsoft https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266(v=vs.85).aspx and explained in this tutorial. https://msdn.microsoft.com/en-us/library/windows/desktop/dd464659(v=vs.85).aspx

Here is a really good blog post about the issue: http://www.hanselman.com/blog/LivingAHighDPIDesktopLifestyleCanBePainful.aspx

**Comment by yermak** [comment]
Thanks for detailed information.
DPI awareness used to be big problem in Java, which I tried to solve years back.
In this particular case - I believe it's just bad UI design from side.
However, I believe I made things better in version 6.4.1 please check
