### ISSUE TITLE
Garbled Text

### ISSUE THREAD

**Issue by spooknik** [yermak/AudioBookConverter#469]
I am trying to run this tool for the first time and the text in the GUI is all garbled. Looks like encoding error maybe? 

I have tried the portable and installed version. 

Using Windows 10 21H2

![image](https://user-images.githubusercontent.com/40317809/233941600-01fe698f-47ae-4ad8-b24f-9ded72a0e48c.png)

**Comment by yermak** [comment]
@spooknik 
You are right that encoding problem, there are many mp3 files which were encoded using "unexpected" charset encoding.
Unfortunately, I don't know the way how to guess charset which creators of mp3 files had in mind when they created tags.
This could explain why filenames are corrupted.

However, your problem looks as you are using "not usual for me" encoding charset in windows.
If this prevents your usage I would recommend to switch to some type of english encoding to see if it works.

Actually, my program does not support additional languages, so, i would expect all labels to stay in english

Does it actually prevent you from encoding?

P.S. especially strange that some labels are fine.

**Comment by spooknik** [comment]
Thanks a lot for the quick reply. 

My Windows is in US English and it's never been anything else. (Keyboard is in Danish.. but I doubt that's an issue)

Current enoding: 
![image](https://user-images.githubusercontent.com/40317809/234010900-843a83ed-d8db-457b-b1e5-4746a00df891.png)

I also tried [repairing / resetting](https://thegeekpage.com/fix-corrupted-fonts-on-windows-10/) the Windows fonts.. but the problem still is there. 

Since no one else reported a similar issue, I assume my problem is limited to this computer. I will attempt to run the program on another computer and see the results.

**Comment by yermak** [comment]
Issue is unclrear
