### ISSUE TITLE
Support flac as source files for audiobook

### ISSUE THREAD

**Issue by yermak** [yermak/AudioBookConverter#47]
Support flac files as source for audiobooks.
Use cue files as source of meta information.

**Comment by Kazaa3** [comment]
I have tried to use lossless audio files as source. FLAC files are not recognized at all. m4a/alac files can in fact be converted (mp42/isom), but are stored in a single audio file. The menu looks like this:

![alac](https://user-images.githubusercontent.com/43350149/77929951-8afc0380-72aa-11ea-96cb-7d22f1c39bca.PNG)

**Comment by yermak** [comment]
@Kazaa3,
got it. 
In fact using m4a/alac will require chapter edditing from issue #49.
So, it's not only codec support it's both: codec and meta information from m4a or cue file

**Comment by yermak** [comment]
Added flac support including loading chapters from cue file.
Support of m4a/alac will follow as loading of meta information same as for m4b.
Will be released shortly.

**Comment by Kazaa3** [comment]
Thank you for this fast update. I tried to covert some test files, and both alac and flac converting is working fine.

**Comment by JakobTischler** [comment]
Hi Yarick. Do I understand you correctly that .cue files are *only* supported for flac files? If so, can you explain why? IMO it'd be a valuable feature to be able to use them for any source file.
