### ISSUE TITLE
File - Add - Files/Folders not opening explorer window

### ISSUE THREAD

**Issue by cryan180** [yermak/AudioBookConverter#473]
I am currently running version 6.1.2
I have uninstalled/rebooted/reinstalled/rebooted 3 times. I also purchased the Steam version per suggestion on the github page with no change.  It was working just fine today and then just stopped working.

**Comment by krejko** [comment]
This just started happening to me on Windows 6.2.10 version. So far I have been unable to figure out how to get the file/folder explorer window to show again. I could convert 10-15 books successfully, but then suddenly the new book -> file/folder buttons stopped letting me add files for a new book.

**Comment by krejko** [comment]
I was just able to locate and delete the AudioBookCoverter folder located in %APPDATA%/Roaming/ and it appears to have resolved the issue. Unless there are hidden files I was unable to see, I am not sure why this fixed the issue as it appeared to only contain a .log file. Anyways, hope this helps debug the issue and/or help someone else get back to using the tool. Besides these few minor issues, I've been really enjoying the tool so I hope this report only helps to make it even better.

**Comment by yermak** [comment]
Please try to use Repair feature in System menu.
