### ISSUE TITLE
Title & Series

### ISSUE THREAD

**Issue by lilibean22** [yermak/AudioBookConverter#478]
I'm trying to edit the Title and Series fields.  They are not the same and when I convert they both end up being the same, what I had in the Series textbox.  I tried 3 times and it always ended up the same.

Also for individual audiobooks (not part of a series) I remove the series text and it adds back in what's in the Title.

**Comment by yermak** [comment]
> Also for individual audiobooks (not part of a series) I remove the series text and it adds back in what's in the Title.

This is expected behavior, they both needed to allow Apple Books Application to group books properly.

>They are not the same and when I convert they both end up being the same, what I had in the Series textbox. 
Which version did you use? I believe current stable version 6.4.1 should work just fine - just recently converted several series myself and all tags are correct.
