### ISSUE TITLE
Image File Saves Automatically

### ISSUE THREAD

**Issue by lilibean22** [yermak/AudioBookConverter#479]
Any time I add a m4b file to program the image file is saved.  I don't want the file saved.

Please give an option to either have the ability to select to save or not, or fix it so it doesn't automatically save.

**Comment by yermak** [comment]
@lilibean22 ,

Could you please explain what do you mean by image file is saved.

**Comment by yermak** [comment]
To close the bug, I will remind there is option to remove image from the book on ArtWork tab, just select image and press remove.
