### ISSUE TITLE
Chapter sorting

### ISSUE THREAD

**Issue by Kazaa3** [yermak/AudioBookConverter#48]
Numbers are not sorted in ascending order if the number of digits is different. Here in the example picture, chapter 2 only appears after chapter 19.
![Chapter sorting](https://user-images.githubusercontent.com/43350149/77927890-09a37180-72a8-11ea-8a22-c8c803f2692f.PNG)

**Comment by yermak** [comment]
There is no good way to guess the sequence as filenames could be very different. You need manually sort them before converting to chapters. 

Good practice is adding leading 0 before all numbers, then alphabetic order works. There are so may forms of filenames. 
I was thinking about option to disply some information from tags and if we lucky to have chapter number as number in title we could resort.
