### ISSUE TITLE
It won't do anything

### ISSUE THREAD

**Issue by ChelseaThomas86** [yermak/AudioBookConverter#487]
I have downloaded some audiobooks with the Libby Firefox Extension.
I want to break them into chapters for my son's Yoto Player. 
I add the MP3 file, when I click on the chapters tab it shows me the chapters. 
I click Start and nothing happens.

What do I do?

**Comment by Marvin-D-Martian** [comment]
I have the same issue. No matter what mp3 files I load, when I press convert nothing happens. No error, nothing at all.
