### ISSUE TITLE
6.1.2 Broken - Cannot see files in chapters tab, cannot start convert, cannot scroll

### ISSUE THREAD

**Issue by thew1se** [yermak/AudioBookConverter#488]
All previous versions have worked without issue. I haven't used audiobook converter in a while, but came back to it for a few more books.  Something has changed with this newest version.   Now I can't downgrade.

1. When adding a folder, files add successfully, but cannot use the up/down scroll bar.
2. When clicking the chapters tab, it changes to the chapters tab, but nothing appears.
3. If I click start, the save dialogue opens, but then nothing happens.

@yermak , are you still maintaining this software?

**Comment by yermak** [comment]
This version did not change for many months...
Did you try with another book?

**Comment by yermak** [comment]
And similar to other similar bugs...
What operating system do you use? What version?
Are you adding files from local drive or network drive? do you have write permissions? 

A little details would help, thanks.

**Comment by thew1se** [comment]
Most of my issues have been fixed with latest release 6.2.10 on windows 11. thank you!

Only thing happening now is the scrolling.   There are no scroll bars to see chapters off screen (more than 15 chapters).  Also when pulling window down from bottom, the files section does not increase, only the window border increases.  Only did one book so far though, I will try others to see if this is related to the book or audiobookconverter. 

![image](https://github.com/yermak/AudioBookConverter/assets/57738712/03618bab-ef2f-4b8b-aed6-6e2ccd8e2e7a)

**Comment by yermak** [comment]
It should be fixed in 6.4.1
