### ISSUE TITLE
M4b M4b Convertion from a High Bit Rate to a Lower Bite does not work.

### ISSUE THREAD

**Issue by OldScotsman** [yermak/AudioBookConverter#494]
When finished editing the chapters in an M4b file I wish to convert the bit rate from 128 Kb to 64 Kb.  The editing works but I can't change the bit rate to anything.
Can you help?
OldScotsman

**Comment by yermak** [comment]
Did you try to set Re-Encoding = Force?

**Comment by OldScotsman** [comment]
Hello "yermak"
Thank you for replying.
There is a Tab called "Force Re-Encoding" with Three choices. Auto/Always/Avoid and I have tried all three with no luck.
Regards
OldScotsman

**Comment by OldScotsman** [comment]
Just to be clear.  I have single M4b Audiobook Files with embedded chapters at 128 Kbps. After editing I now wish to convert them from the 128 Kbps to the smaller 64 Kbps.  The editing works but they file size remains at 128 kbps.

**Comment by yermak** [comment]
Just tested: it does work as expected on my sample (single 128k file to single 64k file - twice smaller file). It could be book/codec specific issue or some strange bug.
You could upload source book into cloud and send me email to my nick at gmail.com - i could try to reproduce the issue.
It would be great if you could give some details if you changed any other settings...

**Comment by OldScotsman** [comment]
Are you sure you are converting M4b 128 Kb to M4b 64 Kb?   It works fine using Mp3 128 Kb to M4b 64 Kb.

**Comment by OldScotsman** [comment]
It now find it converts M4b 128 Kb to M4b 64 Kb as long as I set "Force re-encoded" to always.
Is is possible to make a donation towards this excellent program.

**Comment by yermak** [comment]
Hi @OldScotsman,
Thanks for returning with update. That's how it supposed to work.
Some m4b books use no-standard aac encoders, i.e. apple one. My idea was to allow to keep default encoder quality unless user explicitly Force it to re-encode. 
So it will re-encode to lower bitrate if codec is different i.e. from aac to mp3, but if you keep the same codec (m4b file with aac) by default it will try to re-use existing codec which will be much faster.

I removed donations few years back, if you like the program you can buy it at https://steamcommunity.com/app/1529240/ 
It's the same version, but I release to steam slightly later after better testing, while free version is coming fresh out of the press.
