### ISSUE TITLE
Issues After a Single conversion

### ISSUE THREAD

**Issue by walenchao** [yermak/AudioBookConverter#495]
I started encountering the same behavior a lot of folks seem to have, where the application will launch but clicking Start does not begin the conversion nor load the File Explorer window to select an output directory. 

Deleting the Audiobook Converter folder in %AppData% works temporarily, but the issue reappears after trying to convert another book. A successful conversion yields the following log entry:

[logs.txt](https://github.com/yermak/AudioBookConverter/files/13273779/logs.txt)

After loading up a second title, and not being able to start the conversion, this is the log that appears:
[LogsAfterLoading2ndbook.txt](https://github.com/yermak/AudioBookConverter/files/13273795/LogsAfterLoading2ndbook.txt)

After closing the software completely, then loading it through Steam like normal, it's the same log file. The pertinent bit seems to be this:
```
06-11-2023 16:26:42 WARN  FileDataWriter:195 - Can't open directory channel. Log directory fsync won't be performed.
06-11-2023 16:26:42 INFO  EnvironmentImpl:382 - Exodus environment created: C:\Users\charl\AppData\Roaming\AudiobookConverter-6.1.2
06-11-2023 16:26:42 WARN  FileDataWriter:195 - Can't open directory channel. Log directory fsync won't be performed.
06-11-2023 16:26:42 INFO  EnvironmentImpl:382 - Exodus environment created: C:\Users\charl\AppData\Roaming\AudiobookConverter-6.1.2
```

but I can't really tell. I tried moving the files to the same directory as ABC, I tried doing one file at a time, I tried verifying the Steam cache, the only thing that fixes it is deleting `C:\Users\[username]\AppData\Roaming\AudiobookConverter-6.1.2` completely, then starting the program back up. It will convert 1 book, then fail every time afterwards.

**Comment by yermak** [comment]
What version of Windows you are on?

**Comment by walenchao** [comment]
Windows 11 Home, 10.0.22621 Build 22621

**Comment by yermak** [comment]
I never tested it on Windows 11, but new version released which should be more stable and also has repair feature.
Hope this helps
