### ISSUE TITLE
Was working well but not anymore

### ISSUE THREAD

**Issue by OldScotsman** [yermak/AudioBookConverter#496]
When I load a single M4b book to edited the chapters or to change the bit rate I click on "ADD" I can choose "Files or Folder". 
The file and location is shown but I can no longer highlight it. If I click on "ADD" it comes up "No content in table".
I have tried past files that Audiobook Converter was successful with but they no longer work either.
I have tried deleting the program and reinstalling but still no success.  I contacted a friend who started using your program after I recommended it and but he too has the same problem.
Can you help?
OldScotsman

**Comment by yermak** [comment]
@OldScotsman , please update to new version.
