### ISSUE TITLE
Narrated field parsing

### ISSUE THREAD

**Issue by Kazaa3** [yermak/AudioBookConverter#50]
The Narrator field is not parsed. For this the ID3v2 Tag Composer (TCOM Frame) could be used. Some applications are also writting a Narratedby tag.

EDIT: The album artist tag (TPE2) is used for parsing and works fine, but not all applications are writting it in this style.

![narrated by](https://user-images.githubusercontent.com/43350149/78004305-3738fb00-733a-11ea-89d4-2ecc244b8e83.PNG)

**Comment by Kazaa3** [comment]
Thank you for adding this. Can you maybe also add support for the composer tag if narratedby and albumartist is unset?

**Comment by yermak** [comment]
Added support for both fields. I never saw them set across files I encoded. I believe there is about 80 tags supported, not sure how widely they are used.
