### ISSUE TITLE
Cannot Add Files or Folders on macOS Version

### ISSUE THREAD

**Issue by RushHour2k5** [yermak/AudioBookConverter#522]
I have tried every version since 6.0.0, and I cannot get files or folders to add to the list. Clicking them from the file menu does nothing; clicking them from the add button keeps the menu open and doesn't function as a click, and dragging the file or folder in does nothing. I've tried both on Intel and M2-based MacBooks.

**Comment by yermak** [comment]
@RushHour2k5 ,
With some MacOS update Apple changed security model (about 1 year back) and I can't work around it. I'm not sure if anyone was able to do that. Probably I should stop releaseing Mac version. 

In several other posts I already shared that MacOS native version will be ready soon which will respect apple security - I'm still fighting with some issue.

Sorry, I'm not going to fix this bug, as I'm trying to find time to complete MacOS native version

**Comment by yermak** [comment]
Duplicates #580

**Comment by yermak** [comment]
Beta for Mac OS X is available
https://github.com/yermak/AudioBookConverter/issues/580#issuecomment-2268738667
