### ISSUE TITLE
when playing the m4b file the audio is damaged

### ISSUE THREAD

**Issue by doesn123** [yermak/AudioBookConverter#524]
It sounds like the spoken word is being whistled and also distorted.
I've used this program many times without problems - I haven't changed any settings

**Comment by yermak** [comment]
Did you try to increase bitrate?

**Comment by doesn123** [comment]
Why didn't I think of that...
Solved - thanks! :)

**Comment by yermak** [comment]
@doesn123 , current version of program targets encoding speed and not quality, so you may need to go higher bitrates to get the acceptable results. 
I created a poll for this https://github.com/yermak/AudioBookConverter/discussions/512
