### ISSUE TITLE
Prompt to download new version, even though it is installed

### ISSUE THREAD

**Issue by jimbo1jimbo** [yermak/AudioBookConverter#525]
I have downloaded and installed AudioBookConverter-All-Users-6.2.10.msi (not via Steam)

Even though I have the latest version, when I start the program, I get a prompt to download the new version.

Is there a workaround to stop the check?

**Comment by sgmoore** [comment]
Same happens here. 
I think this is a case-sensitivity issue. It is comparing the contents of https://raw.githubusercontent.com/yermak/AudioBookConverter/version/windows.txt which is

**AudiobookConverter-6.2.10**       but the program version is actually

**AudioBookConverter-6.2.10**

**Comment by jjones3905** [comment]
Yep.

Code from AudiobookConverter.java, lines 174-5

```
String version = readStringFromURL("https://raw.githubusercontent.com/yermak/AudioBookConverter/version/" + platform + ".txt");
if (!Version.getVersionString().equals(StringUtils.trim(version))) {
```

and from Version.java
```
    public static String getVersionString() {
        return "AudioBookConverter-#{APP_VERSION}#";
    }
```

**Comment by yermak** [comment]
This is not a bug :)

**Comment by jjones3905** [comment]
Clever, just getting rid of the alphas in the version so case
sensitivity doesn't intrude :)
