### ISSUE TITLE
Can not load files

### ISSUE THREAD

**Issue by cerinawithasea** [yermak/AudioBookConverter#529]
I can not load any files into the program, This works perfectly for me on windows. On my mac i had to go through the terminal to load the program and now i have tried everything i can think of to load music files and it just stares back at me and laughs

java.specification.version: 17
javafx.runtime.version: 17.0.1+1
sun.jnu.encoding: UTF-8
java.class.path: /Applications/AudiobookConverter.app/Contents/app/lib/audiobookconverter-6.2.10.jar:/Applications/AudiobookConverter.app/Contents/app/lib/AppleJavaExtensions-1.4.jar:/Applications/AudiobookConverter.app/Contents/app/lib/ST4-4.3.4.jar:/Applications/AudiobookConverter.app/Contents/app/lib/antlr-runtime-3.5.3.jar:/Applications/AudiobookConverter.app/Contents/app/lib/checker-qual-3.33.0.jar:/Applications/AudiobookConverter.app/Contents/app/lib/commons-io-2.15.0.jar:/Applications/AudiobookConverter.app/Contents/app/lib/commons-lang3-3.13.0.jar:/Applications/AudiobookConverter.app/Contents/app/lib/controlsfx-11.1.1.jar:/Applications/AudiobookConverter.app/Contents/app/lib/error_prone_annotations-2.18.0.jar:/Applications/AudiobookConverter.app/Contents/app/lib/failureaccess-1.0.1.jar:/Applications/AudiobookConverter.app/Contents/app/lib/ffmpeg-0.6.3-20201115.194337-1.jar:/Applications/AudiobookConverter.app/Contents/app/lib/gson-2.10.1.jar:/Applications/AudiobookConverter.app/Contents/app/lib/guava-32.0.0-jre.jar:/Applications/AudiobookConverter.app/Contents/app/lib/j2objc-annotations-2.8.jar:/Applications/AudiobookConverter.app/Contents/app/lib/javafx-base-17.0.1.jar:/Applications/AudiobookConverter.app/Contents/app/lib/javafx-controls-17.0.1.jar:/Applications/AudiobookConverter.app/Contents/app/lib/javafx-fxml-17.0.1.jar:/Applications/AudiobookConverter.app/Contents/app/lib/javafx-graphics-17.0.1.jar:/Applications/AudiobookConverter.app/Contents/app/lib/javafx-media-17.0.1.jar:/Applications/AudiobookConverter.app/Contents/app/lib/javafx-swing-17.0.1.jar:/Applications/AudiobookConverter.app/Contents/app/lib/jsr305-3.0.2.jar:/Applications/AudiobookConverter.app/Contents/app/lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/Applications/AudiobookConverter.app/Contents/app/lib/modelmapper-0.7.7.jar:/Applications/AudiobookConverter.app/Contents/app/lib/reload4j-1.2.22.jar:/Applications/AudiobookConverter.app/Contents/app/lib/slf4j-api-2.0.9.jar:/Applications/AudiobookConverter.app/Contents/app/lib/slf4j-reload4j-2.0.9.jar
sun.awt.enableExtraMouseButtons: true
java.vm.vendor: Oracle Corporation
sun.arch.data.model: 64
sun.font.fontmanager: sun.font.CFontManager
java.vendor.url: https://java.oracle.com/
user.timezone: America/Toronto
java.vm.specification.version: 17
os.name: Mac OS X
javafx.version: 17.0.1
sun.java.launcher: SUN_STANDARD
user.country: US
sun.boot.library.path: /Applications/AudiobookConverter.app/Contents/runtime/Contents/Home/lib
sun.java.command: uk.yermak.audiobookconverter.AudiobookConverter
http.nonProxyHosts: local|*.local|169.254/16|*.169.254/16
APP_HOME: /Users/cerinawithasea/.abc/AudioBookConverter-6.2.10
jdk.debug: release
sun.cpu.endian: little
jpackage.app-path: /Applications/AudiobookConverter.app/Contents/MacOS/AudiobookConverter
user.home: /Users/cerinawithasea
user.language: en
sun.stderr.encoding: UTF-8
java.specification.vendor: Oracle Corporation
java.version.date: 2021-10-19
java.home: /Applications/AudiobookConverter.app/Contents/runtime/Contents/Home
file.separator: /
java.vm.compressedOopsMode: Zero based
line.separator: 

sun.stdout.encoding: UTF-8
java.vm.specification.vendor: Oracle Corporation
java.specification.name: Java Platform API Specification
sun.management.compiler: HotSpot 64-Bit Tiered Compilers
ftp.nonProxyHosts: local|*.local|169.254/16|*.169.254/16
java.runtime.version: 17.0.1+12-39
user.name: cerinawithasea
path.separator: :
os.version: 12.6.8
java.runtime.name: OpenJDK Runtime Environment
file.encoding: UTF-8
java.vm.name: OpenJDK 64-Bit Server VM
java.vendor.url.bug: https://bugreport.java.com/bugreport/
java.io.tmpdir: /var/folders/4d/wpbq3wk9313_xtf1y8j776f00000gn/T/
java.version: 17.0.1
user.dir: /Applications/AudiobookConverter.app
jpackage.app-version: 6.2.10
os.arch: x86_64
java.vm.specification.name: Java Virtual Machine Specification
native.encoding: UTF-8
java.library.path: :/Applications/AudiobookConverter.app/Contents/app:/Users/cerinawithasea/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
java.vm.info: mixed mode
java.vendor: Oracle Corporation
java.vm.version: 17.0.1+12-39
https.protocols: TLSv1,TLSv1.1,TLSv1.2
sun.io.unicode.encoding: UnicodeBig
socksNonProxyHosts: local|*.local|169.254/16|*.169.254/16
java.class.version: 61.0

{"darkMode":false,"lastUsedPreset":0,"presets":[{"name":"iphone","format":{"name":"ipod","codec":"aac","extension":"m4b","compatibleCodecs":["alac"]},"bitRate":64,"frequency":44100,"channels":2,"vbrQuality":4,"cbr":true,"cutoff":12000,"speed":1.0,"force":"Auto","splitChapters":false},{"name":"ipod nano","format":{"name":"ipod","codec":"aac","extension":"m4b","compatibleCodecs":["alac"]},"bitRate":64,"frequency":44100,"channels":1,"vbrQuality":2,"cbr":false,"cutoff":10000,"speed":1.0,"force":"Auto","splitChapters":false},{"name":"ipod classic","format":{"name":"ipod","codec":"aac","extension":"m4b","compatibleCodecs":["alac"]},"bitRate":96,"frequency":44100,"channels":2,"vbrQuality":3,"cbr":true,"cutoff":12000,"speed":1.0,"force":"Auto","splitChapters":false},{"name":"android 5+","format":{"name":"ogg","codec":"libopus","extension":"ogg","compatibleCodecs":["vorbis"]},"bitRate":64,"frequency":48000,"channels":2,"vbrQuality":3,"cbr":false,"cutoff":12000,"speed":1.0,"force":"Auto","splitChapters":false},{"name":"android old","format":{"name":"ipod","codec":"aac","extension":"m4b","compatibleCodecs":["alac"]},"bitRate":96,"frequency":44100,"channels":2,"vbrQuality":3,"cbr":true,"cutoff":10000,"speed":1.0,"force":"Auto","splitChapters":false},{"name":"legacy","format":{"name":"mp3","codec":"libmp3lame","extension":"mp3","compatibleCodecs":[]},"bitRate":128,"frequency":44100,"channels":2,"vbrQuality":3,"cbr":true,"cutoff":12000,"speed":1.0,"force":"Auto","splitChapters":true}],"genres":[],"chapterFormat":"\u003cif(BOOK_NUMBER)\u003e\u003cBOOK_NUMBER\u003e. \u003cendif\u003e\u003cif(BOOK_TITLE)\u003e\u003cBOOK_TITLE\u003e. \u003cendif\u003e\u003cif(CHAPTER_TEXT)\u003e\u003cCHAPTER_TEXT\u003e \u003cendif\u003e\u003cif(CHAPTER_NUMBER)\u003e\u003cCHAPTER_NUMBER; format\u003d\"%,03d\"\u003e \u003cendif\u003e\u003cif(TAG)\u003e\u003cTAG\u003e \u003cendif\u003e\u003cif(CUSTOM_TITLE)\u003e\u003cCUSTOM_TITLE\u003e \u003cendif\u003e\u003cif(DURATION)\u003e - \u003cDURATION; format\u003d\"%02d:%02d:%02d\"\u003e\u003cendif\u003e","filenameFormat":"\u003cWRITER\u003e\u003cif(SERIES)\u003e - [\u003cSERIES\u003e\u003cif(BOOK_NUMBER)\u003e - \u003cBOOK_NUMBER; format\u003d\"%,02d\"\u003e\u003cendif\u003e]\u003cendif\u003e - \u003cTITLE\u003e\u003cif(NARRATOR)\u003e (\u003cNARRATOR\u003e)\u003cendif\u003e","partFormat":"\u003cif(WRITER)\u003e\u003cWRITER\u003e \u003cendif\u003e\u003cif(SERIES)\u003e- [\u003cSERIES\u003e\u003cif(BOOK_NUMBER)\u003e -\u003cBOOK_NUMBER\u003e\u003cendif\u003e] - \u003cendif\u003e\u003cif(TITLE)\u003e\u003cTITLE\u003e\u003cendif\u003e\u003cif(NARRATOR)\u003e (\u003cNARRATOR\u003e)\u003cendif\u003e\u003cif(YEAR)\u003e-\u003cYEAR\u003e\u003cendif\u003e\u003cif(PART)\u003e, Part \u003cPART; format\u003d\"%,03d\"\u003e\u003cendif\u003e","chapterContext":"CHAPTER_NUMBER:CHAPTER_TEXT:DURATION","chapterCustomTitle":"","outputFolder":"/Users/cerinawithasea","sourceFolder":"/Users/cerinawithasea"}

**Comment by yermak** [comment]
I will not fix mac issues, they changed security policy accessing to files, which is very difficult to workaround from Java.
I'm in progress of getting native mac version ready, just stuck with logistic
