### ISSUE TITLE
App window size

### ISSUE THREAD

**Issue by ZYZZYX6x942** [yermak/AudioBookConverter#535]
I Can't see the bottom of the app window. Resizing, maximizing and minimizing don't help.
java.specification.version: 17
javafx.runtime.version: 17.0.1+1
sun.cpu.isalist: amd64
sun.jnu.encoding: Cp1252
java.class.path: C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\audiobookconverter-6.2.10.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\antlr-runtime-3.5.3.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\AppleJavaExtensions-1.4.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\checker-qual-3.33.0.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\commons-io-2.15.0.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\commons-lang3-3.13.0.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\controlsfx-11.1.1.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\error_prone_annotations-2.18.0.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\failureaccess-1.0.1.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\ffmpeg-0.6.3-20201115.194337-1.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\gson-2.10.1.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\guava-32.0.0-jre.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\j2objc-annotations-2.8.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\javafx-base-17.0.1.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\javafx-controls-17.0.1.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\javafx-fxml-17.0.1.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\javafx-graphics-17.0.1.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\javafx-media-17.0.1.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\javafx-swing-17.0.1.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\jsr305-3.0.2.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\modelmapper-0.7.7.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\reload4j-1.2.22.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\slf4j-api-2.0.9.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\slf4j-reload4j-2.0.9.jar;C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\ST4-4.3.4.jar
sun.awt.enableExtraMouseButtons: true
java.vm.vendor: Oracle Corporation
sun.arch.data.model: 64
user.variant: 
java.vendor.url: https://java.oracle.com/
user.timezone: America/Los_Angeles
java.vm.specification.version: 17
os.name: Windows 10
javafx.version: 17.0.1
sun.java.launcher: SUN_STANDARD
user.country: US
sun.boot.library.path: C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\runtime\bin
sun.java.command: uk.yermak.audiobookconverter.AudiobookConverter
APP_HOME: C:\Users\denbe\AppData\Roaming\AudioBookConverter-6.2.10
jdk.debug: release
sun.cpu.endian: little
jpackage.app-path: C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\AudioBookConverter.exe
user.home: C:\Users\denbe
user.language: en
java.specification.vendor: Oracle Corporation
java.version.date: 2021-10-19
java.home: C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter\runtime
file.separator: \
java.vm.compressedOopsMode: Zero based
line.separator: 

java.vm.specification.vendor: Oracle Corporation
java.specification.name: Java Platform API Specification
user.script: 
sun.management.compiler: HotSpot 64-Bit Tiered Compilers
java.runtime.version: 17.0.1+12-39
user.name: denbe
path.separator: ;
os.version: 10.0
java.runtime.name: OpenJDK Runtime Environment
file.encoding: Cp1252
java.vm.name: OpenJDK 64-Bit Server VM
java.vendor.url.bug: https://bugreport.java.com/bugreport/
java.io.tmpdir: C:\Users\denbe\AppData\Local\Temp\
java.version: 17.0.1
user.dir: C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter
jpackage.app-version: 6.2.10
os.arch: amd64
java.vm.specification.name: Java Virtual Machine Specification
sun.os.patch.level: 
native.encoding: Cp1252
java.library.path: C:\Program Files (x86)\Steam\steamapps\common\AudioBookConverter\AudioBookConverter;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\Steam;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Calibre2\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\dotnet\;C:\Users\denbe\AppData\Local\Microsoft\WindowsApps;;.
java.vm.info: mixed mode
java.vendor: Oracle Corporation
java.vm.version: 17.0.1+12-39
https.protocols: TLSv1,TLSv1.1,TLSv1.2
sun.io.unicode.encoding: UnicodeLittle
java.class.version: 61.0

{"darkMode":true,"lastUsedPreset":0,"presets":[{"name":"iphone","format":{"name":"ipod","codec":"aac","extension":"m4b","compatibleCodecs":["alac"]},"bitRate":128,"frequency":44100,"channels":2,"vbrQuality":4,"cbr":true,"cutoff":8000,"speed":1.0,"force":"Auto","splitChapters":false},{"name":"ipod nano","format":{"name":"ipod","codec":"aac","extension":"m4b","compatibleCodecs":["alac"]},"bitRate":64,"frequency":44100,"channels":1,"vbrQuality":2,"cbr":false,"cutoff":10000,"speed":1.0,"force":"Auto","splitChapters":false},{"name":"ipod classic","format":{"name":"ipod","codec":"aac","extension":"m4b","compatibleCodecs":["alac"]},"bitRate":96,"frequency":44100,"channels":2,"vbrQuality":3,"cbr":true,"cutoff":12000,"speed":1.0,"force":"Auto","splitChapters":false},{"name":"android 5+","format":{"name":"ogg","codec":"libopus","extension":"ogg","compatibleCodecs":["vorbis"]},"bitRate":64,"frequency":48000,"channels":2,"vbrQuality":3,"cbr":false,"cutoff":12000,"speed":1.0,"force":"Auto","splitChapters":false},{"name":"android old","format":{"name":"ipod","codec":"aac","extension":"m4b","compatibleCodecs":["alac"]},"bitRate":96,"frequency":44100,"channels":2,"vbrQuality":3,"cbr":true,"cutoff":10000,"speed":1.0,"force":"Auto","splitChapters":false},{"name":"legacy","format":{"name":"mp3","codec":"libmp3lame","extension":"mp3","compatibleCodecs":[]},"bitRate":128,"frequency":44100,"channels":2,"vbrQuality":3,"cbr":true,"cutoff":12000,"speed":1.0,"force":"Auto","splitChapters":true}],"genres":["","Audio Book","Audiobook","Audiobook - Fantasy","Audio book","Fantasy"],"chapterFormat":"\u003cif(BOOK_NUMBER)\u003e\u003cBOOK_NUMBER\u003e. \u003cendif\u003e\u003cif(BOOK_TITLE)\u003e\u003cBOOK_TITLE\u003e. \u003cendif\u003e\u003cif(CHAPTER_TEXT)\u003e\u003cCHAPTER_TEXT\u003e \u003cendif\u003e\u003cif(CHAPTER_NUMBER)\u003e\u003cCHAPTER_NUMBER; format\u003d\"%,03d\"\u003e \u003cendif\u003e\u003cif(TAG)\u003e\u003cTAG\u003e \u003cendif\u003e\u003cif(CUSTOM_TITLE)\u003e\u003cCUSTOM_TITLE\u003e \u003cendif\u003e\u003cif(DURATION)\u003e - \u003cDURATION; format\u003d\"%02d:%02d:%02d\"\u003e\u003cendif\u003e","filenameFormat":"\u003cWRITER\u003e\u003cif(SERIES)\u003e - [\u003cSERIES\u003e\u003cif(BOOK_NUMBER)\u003e - \u003cBOOK_NUMBER; format\u003d\"%,02d\"\u003e\u003cendif\u003e]\u003cendif\u003e - \u003cTITLE\u003e\u003cif(NARRATOR)\u003e (\u003cNARRATOR\u003e)\u003cendif\u003e","partFormat":"\u003cif(WRITER)\u003e\u003cWRITER\u003e \u003cendif\u003e\u003cif(SERIES)\u003e- [\u003cSERIES\u003e\u003cif(BOOK_NUMBER)\u003e -\u003cBOOK_NUMBER\u003e\u003cendif\u003e] - \u003cendif\u003e\u003cif(TITLE)\u003e\u003cTITLE\u003e\u003cendif\u003e\u003cif(NARRATOR)\u003e (\u003cNARRATOR\u003e)\u003cendif\u003e\u003cif(YEAR)\u003e-\u003cYEAR\u003e\u003cendif\u003e\u003cif(PART)\u003e, Part \u003cPART; format\u003d\"%,03d\"\u003e\u003cendif\u003e","chapterContext":"CHAPTER_NUMBER:CHAPTER_TEXT:DURATION","chapterCustomTitle":"","outputFolder":"C:\\Users\\denbe\\OneDrive\\Desktop\\Ursula K. Le Guin","sourceFolder":"C:\\Users\\denbe\\OneDrive\\Desktop\\Isaac Asimov\\Non-fiction\\1981 - Asimov\u0027s Guide to the Bible (Harpenau) 64k 41.51.42 {1.14gb}"}

![image](https://github.com/yermak/AudioBookConverter/assets/159497207/a724c4e3-d864-4267-9c43-128f999f1a4b)
![converter](https://github.com/yermak/AudioBookConverter/assets/159497207/c50b7311-0f6e-445c-99f2-474f20bab465)

**Comment by yermak** [comment]
Could you please advise what screen resolution do you have and what is your scaling settings.
From screenshots it seems quite non-standard configuration.

**Comment by SomayaKahwa** [comment]
i have the same issue

**Comment by Hachdog** [comment]
Same here on a 1920x1080 150%ppi

**Comment by ZYZZYX6x942** [comment]
150% size. (recommended) 1929 x 1080 (recommended) I tried changing it. no effect

**Comment by yermak** [comment]
Fixed in 6.4.1
