### ISSUE TITLE
Converter generates as many .m4b output files as there are mp3 files as input instead of combining

### ISSUE THREAD

**Issue by fredpinchon** [yermak/AudioBookConverter#537]
I am trying to combine many MP3 files into a unique m4b audio book, but despite all the settings attempts, I'm getting as many outputs as I have inputs instead of chapters of a unique file...

java.specification.version: 17
javafx.runtime.version: 17.0.1+1
sun.cpu.isalist: amd64
sun.jnu.encoding: Cp1252
java.class.path: D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\audiobookconverter-6.2.10.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\antlr-runtime-3.5.3.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\AppleJavaExtensions-1.4.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\checker-qual-3.33.0.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\commons-io-2.15.0.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\commons-lang3-3.13.0.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\controlsfx-11.1.1.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\error_prone_annotations-2.18.0.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\failureaccess-1.0.1.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\ffmpeg-0.6.3-20201115.194337-1.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\gson-2.10.1.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\guava-32.0.0-jre.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\j2objc-annotations-2.8.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\javafx-base-17.0.1.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\javafx-controls-17.0.1.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\javafx-fxml-17.0.1.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\javafx-graphics-17.0.1.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\javafx-media-17.0.1.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\javafx-swing-17.0.1.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\jsr305-3.0.2.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\modelmapper-0.7.7.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\reload4j-1.2.22.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\slf4j-api-2.0.9.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\slf4j-reload4j-2.0.9.jar;D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\app\lib\ST4-4.3.4.jar
sun.awt.enableExtraMouseButtons: true
java.vm.vendor: Oracle Corporation
sun.arch.data.model: 64
user.variant: 
java.vendor.url: https://java.oracle.com/
user.timezone: America/Los_Angeles
java.vm.specification.version: 17
os.name: Windows 10
javafx.version: 17.0.1
sun.java.launcher: SUN_STANDARD
user.country: US
sun.boot.library.path: D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\runtime\bin
sun.java.command: uk.yermak.audiobookconverter.AudiobookConverter
APP_HOME: C:\Users\frede\AppData\Roaming\AudioBookConverter-6.2.10
jdk.debug: release
sun.cpu.endian: little
jpackage.app-path: D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\AudioBookConverter.exe
user.home: C:\Users\frede
user.language: en
java.specification.vendor: Oracle Corporation
java.version.date: 2021-10-19
java.home: D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter\runtime
file.separator: \
java.vm.compressedOopsMode: Zero based
line.separator: 

java.vm.specification.vendor: Oracle Corporation
java.specification.name: Java Platform API Specification
user.script: 
sun.management.compiler: HotSpot 64-Bit Tiered Compilers
java.runtime.version: 17.0.1+12-39
user.name: frede
path.separator: ;
os.version: 10.0
java.runtime.name: OpenJDK Runtime Environment
file.encoding: Cp1252
java.vm.name: OpenJDK 64-Bit Server VM
java.vendor.url.bug: https://bugreport.java.com/bugreport/
java.io.tmpdir: C:\Users\frede\AppData\Local\Temp\
java.version: 17.0.1
user.dir: D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter
jpackage.app-version: 6.2.10
os.arch: amd64
java.vm.specification.name: Java Virtual Machine Specification
sun.os.patch.level: 
native.encoding: Cp1252
java.library.path: D:\SteamLibrary\steamapps\common\AudioBookConverter\AudioBookConverter;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\libnvvp;C:\Python310\Scripts\;C:\Python310\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Google\Google Apps Sync\;C:\Program Files\Google\Google Apps Migration\;C:\Program Files\dotnet\;C:\Program Files\Calibre2\;C:\Program Files\PuTTY\;C:\Program Files\WireGuard\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\NVIDIA Corporation\Nsight Compute 2021.1.0\;C:\Program Files\FileBot\;C:\Users\frede\AppData\Local\Microsoft\WindowsApps;C:\Users\frede\AppData\Local\GitHubDesktop\bin;C:\Users\frede\AppData\Roaming\npm;C:\Users\frede\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\JetBrains\DataGrip 2023.3.2\bin;;.
java.vm.info: mixed mode
java.vendor: Oracle Corporation
java.vm.version: 17.0.1+12-39
https.protocols: TLSv1,TLSv1.1,TLSv1.2
sun.io.unicode.encoding: UnicodeLittle
java.class.version: 61.0

{"darkMode":false,"lastUsedPreset":0,"presets":[{"name":"iphone","format":{"name":"ipod","codec":"aac","extension":"m4b","compatibleCodecs":["alac"]},"bitRate":128,"frequency":44100,"channels":2,"vbrQuality":4,"cbr":true,"cutoff":12000,"speed":1.0,"force":"Auto","splitChapters":true},{"name":"ipod nano","format":{"name":"ipod","codec":"aac","extension":"m4b","compatibleCodecs":["alac"]},"bitRate":64,"frequency":44100,"channels":1,"vbrQuality":2,"cbr":false,"cutoff":10000,"speed":1.0,"force":"Auto","splitChapters":false},{"name":"ipod classic","format":{"name":"ipod","codec":"aac","extension":"m4b","compatibleCodecs":["alac"]},"bitRate":96,"frequency":44100,"channels":2,"vbrQuality":3,"cbr":true,"cutoff":12000,"speed":1.0,"force":"Auto","splitChapters":false},{"name":"android 5+","format":{"name":"ogg","codec":"libopus","extension":"ogg","compatibleCodecs":["vorbis"]},"bitRate":64,"frequency":48000,"channels":2,"vbrQuality":3,"cbr":false,"cutoff":12000,"speed":1.0,"force":"Auto","splitChapters":false},{"name":"android old","format":{"name":"ipod","codec":"aac","extension":"m4b","compatibleCodecs":["alac"]},"bitRate":96,"frequency":44100,"channels":2,"vbrQuality":3,"cbr":true,"cutoff":10000,"speed":1.0,"force":"Auto","splitChapters":false},{"name":"legacy","format":{"name":"mp3","codec":"libmp3lame","extension":"mp3","compatibleCodecs":[]},"bitRate":128,"frequency":44100,"channels":2,"vbrQuality":3,"cbr":true,"cutoff":12000,"speed":1.0,"force":"Auto","splitChapters":true}],"genres":["Podcast"],"chapterFormat":"\u003cif(BOOK_NUMBER)\u003e\u003cBOOK_NUMBER\u003e. \u003cendif\u003e\u003cif(BOOK_TITLE)\u003e\u003cBOOK_TITLE\u003e. \u003cendif\u003e\u003cif(CHAPTER_TEXT)\u003e\u003cCHAPTER_TEXT\u003e \u003cendif\u003e\u003cif(CHAPTER_NUMBER)\u003e\u003cCHAPTER_NUMBER; format\u003d\"%,03d\"\u003e \u003cendif\u003e\u003cif(TAG)\u003e\u003cTAG\u003e \u003cendif\u003e\u003cif(CUSTOM_TITLE)\u003e\u003cCUSTOM_TITLE\u003e \u003cendif\u003e\u003cif(DURATION)\u003e - \u003cDURATION; format\u003d\"%02d:%02d:%02d\"\u003e\u003cendif\u003e","filenameFormat":"\u003cWRITER\u003e\u003cif(SERIES)\u003e - [\u003cSERIES\u003e\u003cif(BOOK_NUMBER)\u003e - \u003cBOOK_NUMBER; format\u003d\"%,02d\"\u003e\u003cendif\u003e]\u003cendif\u003e - \u003cTITLE\u003e\u003cif(NARRATOR)\u003e (\u003cNARRATOR\u003e)\u003cendif\u003e","partFormat":"\u003cif(WRITER)\u003e\u003cWRITER\u003e \u003cendif\u003e\u003cif(SERIES)\u003e- [\u003cSERIES\u003e\u003cif(BOOK_NUMBER)\u003e -\u003cBOOK_NUMBER\u003e\u003cendif\u003e] - \u003cendif\u003e\u003cif(TITLE)\u003e\u003cTITLE\u003e\u003cendif\u003e\u003cif(NARRATOR)\u003e (\u003cNARRATOR\u003e)\u003cendif\u003e\u003cif(YEAR)\u003e-\u003cYEAR\u003e\u003cendif\u003e\u003cif(PART)\u003e, Part \u003cPART; format\u003d\"%,03d\"\u003e\u003cendif\u003e","chapterContext":"CHAPTER_NUMBER:CHAPTER_TEXT:DURATION","chapterCustomTitle":"","outputFolder":"D:\\Livres\\Audio Book","sourceFolder":"C:\\Users\\frede"}

**Comment by yermak** [comment]
Hey @fredpinchon 

Look into quality tab, there is a setting "split by" Parts or Chapters. According to you settings you have selected split by chapters, which mean each file from you input will create a chapter and each chapter will be used as output file. So, effectively you don't combine book.
You need to select split by Part, by default there is one part, but if you converting book series in one go - you may want to split book into many parts.

I hope it helps.
