### ISSUE TITLE
Some converted files don't appear in apple books widget

### ISSUE THREAD

**Issue by TheByteSmasher** [yermak/AudioBookConverter#542]
I have converted (from mp3) books and re-chapterized existing mp4 files (whether or not re-encode is selected). Some of these files play fine in apple books and appear as expected in the widget. Some files play fine but WON'T  appear in the widget. The original files (when AudioBookConverter was used to re-chapterize) appear in the widget but the re-chapterized files won't. I've encountered this with some other converters and it has something to do with the encoding or metadata, I think.

**Comment by yermak** [comment]
This is too generic issue, I can't fix it. Need version, settings, links to source files, etc.
