### ISSUE TITLE
Failed to measure available space: The specified location is not supported

### ISSUE THREAD

**Issue by Casuallynoted** [yermak/AudioBookConverter#543]
Getting the above error when trying to select an audiobook file to convert. It then fails due to "not having enough space", despite 1.7TB being available on the drive.

**Comment by yermak** [comment]
For conversion it uses temp directory, which is normally on you main drive. So, even if target drive has space, but you run low on temp directory this may cause an error.

**Comment by Casuallynoted** [comment]
You’re right, that was exactly it! I checked the temp directory space and another app was using it. Closed that and all is well!
