### ISSUE TITLE
Support for batch convert

### ISSUE THREAD

**Issue by Sparh4wk** [yermak/AudioBookConverter#548]
Hi,

is it possible to add batch convert to your program?

I have like 2500 audiobooks and I want to convert them to m4b.
My dir tree is something like

root folder--> book 1 folder --> mp3 files
root folder--> book 2 folder --> mp3 files
root folder--> book 3 folder --> mp3 files
etc..

So I would like to see feature, that I can choose the root folder and just let it convert all the books at once. 

Thanks for reply

**Comment by yermak** [comment]
I was thinking about this for series of books, I don't think it's practical for random set of books as you won't be able to provide meta information...
But, unfortunately, it's not going to happen soon.

**Comment by yermak** [comment]
I will close this issue, as it's not planned to make batch converstions outside of book series
