### ISSUE TITLE
File Truncating

### ISSUE THREAD

**Issue by Heyou66** [yermak/AudioBookConverter#55]
I am using v4.5.2. I believe there is a problem with the mp3 conversion to m4b files. I have not tried any other version, but the program is truncating parts of each mp3 file when creating one .m4b file.  Chapter 2 it was just a few seconds but at the end of chapter 5 it took out 30 seconds.  I went back and check all the original mp3 and they are all good, I then rebuilt the m4b with the same mp3 files in AudioBookConverter and it had the same problem, a total of 2 min had been clipped from the book, all at the end of each mp3.  I used the same mp3’s and converted them to m4a in iTunes and ran those files thru AudioBookConverter and the m4b came out at the correct length with no truncating of the chapters.  Don’t think it would make a difference but the mp3 were all 48bit 22.05kHz 1 channel. When I get the chance, I’ll try some other mp3’s. Has anyone else experienced this problem?

**Comment by yermak** [comment]
sounds like a serious issue.
i will try to reproduce tonight.
could you please advise if your mp3 file were vbr?

**Comment by Heyou66** [comment]
I have found that some mp3s I have are showing the wrong length in MediaInfo and Windows while programs like iTunes and Adobe Audition show the file at the correct length.  My assumption is that AudioBookConverter is pulling the file length from one of these sources and that was why my chapters became truncated.  Why do some mp3 show an incorrect length in windows and others do not? I don’t know.  
Below is info about the files I was playing with, maybe someone knows why this happens, is it bad files, bad conversions to mp3s.  I’ve checked the files on two windows machines one running windows 8 the other windows 10, both gave the same info.
For now my solution is to let iTunes do the conversion to .m4a then let AudioBookConvert create the m4b.

Looking at just one of the files, (file 2).
Using MediaInfo
Audio
Format                           : MPEG Audio
Format_Version                   : Version 2
Format_Profile                   : Layer 3
Duration/String                  : 59 min 9 s
BitRate_Mode/String              : Constant
BitRate/String                   : 48.0 kb/s
Channel(s)/String                : 1 channel
SamplingRate/String              : 22.05 kHz
FrameRate/String                 : 38.281 FPS (576 SPF)
Compression_Mode/String          : Lossy
StreamSize/String                : 20.3 MiB (100%)

Here is the very weird thing. The file is reporting the wrong length.
Windows Properties:  00:59:09
MediaInfo: 59 min 9s
Adobe Audition: 59:26.296
iTunes: 59:26.158
VLC player on my Mac: 59:26

As you can see Windows and MediaInfo are reporting the wrong length, however Windows Media Player reports the wrong length, but plays the whole file correctly.

When I convert all the mp3s in the book with iTunes to .m4a files then run them thru AudioBookConverter I get the following:
Menu 1
ID                                       : 2
Codec ID                                 : text
Duration                                 : 8 h 46 min
Language                                 : English
Bit rate mode                            : CBR
Menu For                                 : 1
00:00:00.000                             :  Chapter 1.  - 00:11:21
00:11:21.273                             :  Chapter 2.  - 00:59:26
01:10:47.579                             :  Chapter 3.  - 01:24:45
02:35:33.121                             :  Chapter 4.  - 01:07:57
03:43:30.174                             :  Chapter 5.  - 01:24:51
05:08:21.567                             :  Chapter 6.  - 01:49:14
06:57:36.467                             :  Chapter 7.  - 00:34:38
07:32:14.653                             :  Chapter 8.  - 00:52:25
08:24:39.935                             :  Chapter 9.  - 00:22:16

When I run the .mp3’s thru AudioBookConverter without converting with iTunes I get:
Menu 1
ID                                       : 2
Codec ID                                 : text
Duration                                 : 8 h 44 min
Language                                 : English
Bit rate mode                            : CBR
Menu For                                 : 1
00:00:00.000                             :  Chapter 1.  - 00:11:18
00:11:18.127                             :  Chapter 2.  - 00:59:09
01:10:27.642                             :  Chapter 3.  - 01:24:21
02:34:49.317                             :  Chapter 4.  - 01:07:37
03:42:27.158                             :  Chapter 5.  - 01:24:27
05:06:54.683                             :  Chapter 6.  - 01:48:44
06:55:38.754                             :  Chapter 7.  - 00:34:28
07:30:07.101                             :  Chapter 8.  - 00:52:10
08:22:17.548                             :  Chapter 9.  - 00:22:10

**Comment by yermak** [comment]
@Heyou66, thank you very much for all details.
If you could do simple test - download version 4.3.0 and retest your book, this will let me identify if this newly intoduced bug (what i suspect as i have done some changes with duration) or is it something which existed for long time for some type of files.

Really apprecaite your help!

**Comment by Heyou66** [comment]
Yes, just checked version 4.3.0 and it worked.  None of the chapters were truncated.
I also tested it with version 4.4.0 and the problem was there.
I hope this help, let me know if I can do anything else.
Thanks for the great software, I've been using chapter and verse but it has a 32bit limitation to file size and length and the author hasn't updated it in years. So very happy to have found your software.  At some point I'll post a feature request mostly to due with metadata, but I want to play with the software more first.

**Comment by yermak** [comment]
@Heyou66,
thank you very much for confirming - that what I was expecting, as I did quite a few changes to support flac and m4b as sources, there was a chance I could break something starting from 4.4.0. 
there is large weekend coming with not a lot of options what to do, so I plan to fix it quite shortly.

**Comment by HenryMontrose** [comment]
I have gone right back to version 4.2, very quick, no lags, and does what I want, converts mp3 to mp4b,  in 1 file to use in my ipod ....no fuss no muss

**Comment by yermak** [comment]
@HenryMontrose, thanks for confirming - i will work on returning back on track with performance and quality ;)

**Comment by yermak** [comment]
Fixed in 4.6.0
