### ISSUE TITLE
AAC support

### ISSUE THREAD

**Issue by Kazaa3** [yermak/AudioBookConverter#56]
I demuxed some mp4 files and tried to drag and drop the resulting .acc files into AudioBookConverter. I realized that only .m1a containered acc's are supported (MPEG-4). Is it possible to also add blank .acc support (MPEG-2), please :)

**Comment by yermak** [comment]
Should be possible, may work just out of the box. Will test it shortly.
Just to confirm, do you mean aac? Or really acc?

**Comment by Kazaa3** [comment]
Oh Sorry, i mean AAC (Advanced Audio Coding) with ADTS-Container (.aac), I tried to drag and drop and AudioBookConverter didn't took the file. Then I rename the file to .m1a and it was possible to start the convert process, but the the program freezes and the audiobook couldn't be finished.

**Comment by yermak** [comment]
Thanks for clarification will check.

**Comment by yermak** [comment]
Hm, I think that actually after you rename file it should work, however, progress bar stucks, but book may actually be created.
I will release experimental version supporting raw aac shortly.

**Comment by yermak** [comment]
Fixed
