### ISSUE TITLE
Chocolatey

### ISSUE THREAD

**Issue by 1kamma** [yermak/AudioBookConverter#57]
I suggest you to create a [Chocolatey ](http://chocolatey.org/)Package, so everyone can download it easily.

**Comment by yermak** [comment]
I will have a look at it, i'm not sure about "everyone" as most of the normal users never heard of it.
Putting it to windows store would be my preference, however, Microsoft does not support java applications inside its store.

Generally, I like idea to have proper package management on windows.

**Comment by yermak** [comment]
I pushed the build of verion 5.0.0 to Chocolately, will see how long it takes them to moderate.
Longer term it's interesting idea, as I could stop distribute ffmpeg and potentially mp4v2.

Will keep this ticket open, until Chocolately is implemented properly.

**Comment by yermak** [comment]
You could try
choco install audiobookconverter --version=5.0.0

Package is still unlisted pending moderator review.

**Comment by 1kamma** [comment]
somehow, v5 does not starting for me

**Comment by yermak** [comment]
Did you install from Chocolatey?

**Comment by 1kamma** [comment]
yes, I installed firstly from the regular download (and it is not starting), and than, from Chocolatey (and still nothing)

**Comment by yermak** [comment]
Do you have any error messages?

**Comment by yermak** [comment]
Unfortunately, I can't upgrade it, before they approve previous version. Thus chocolaty will be on hold for now...

> Attempting to push audiobookconverter.5.1.0.nupkg to https://push.chocolatey.org/
> Failed to process request. 'The package audiobookconverter have a previous version in a submitted state, and no approved stable releases.'.
> The remote server returned an error: (403) Forbidden..

**Comment by yermak** [comment]
Chocolaty package is fully approved and available.
