### ISSUE TITLE
Window does not fit into screen in release 5.00 beta

### ISSUE THREAD

**Issue by HenryMontrose** [yermak/AudioBookConverter#58]
Does not fit on a page any longer, you cannot find let alone use.. min max close.. there is also no room to see genre tab any longer ..

![Screenshot (3)](https://user-images.githubusercontent.com/61348379/79112793-4e82da00-7d77-11ea-8a91-2db797ffb4d6.png)

**Comment by Kazaa3** [comment]
This seems to happen when the scaling in windows 10 is set higher then 100% (and the resolution 1080p or less).

**Comment by yermak** [comment]
Hi,
Yes, this is definitely scaling problem. There is an option to disable it
completely, but UI still needs to be improved as even resizing of window
does not work properly

**Comment by HenryMontrose** [comment]
You have a serious fan here, I sincerely hope you do not mind me adding the issues..
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


14 Apr 2020, 07:37 by notifications@github.com:

>
>
>
> Hi,
>  Yes, this is definitely scaling problem. There is an option to disable it
>  completely, but UI still needs to be improved as even resizing of window
>  does not work properly
>

**Comment by yermak** [comment]
@HenryMontrose , absolutely not, your feedback is very important.

Please feel free to post all ideas/bugs you see. This scaling issue - is critical.

**Comment by yermak** [comment]
I believe UI improved since then, so i close the issue
