### ISSUE TITLE
Cannot change chapter numbers from 3 digits to 2

### ISSUE THREAD

**Issue by PepperRobb97** [yermak/AudioBookConverter#596]
Version 6.4.2
Windows 11 pro
Tried with both Single installation and portable 

Under the settings area, I'm able to adjust the settings for both Book Filename Template and Book Part Filename Template. However, for some reason I am unable to adjust the Chapter Template setting at all. Specifically, I am trying to adjust the 

Chapter_Number; format=%03d" to be %02d' 

so that my chapters only appear to have 2 digits instead of 3. This has been an issue in previous versions as I wasn't able to utilize the "properties" file as it was always previously missing. I have been using version 5.6.2 portable up until this point as this has been the only version that will allow me to edit the properties file and change all of the settings we can change in this version now (which is great!!)

![Screenshot 2024-06-02 053223](https://github.com/yermak/AudioBookConverter/assets/101477181/17454f2f-65cd-4c93-866e-37bbf00410af)

Whenever I go in to change this setting specifically under the Chapter template area and hit ok, I find if I go back in to the settings, the changes under the Chapter Template area revert back again to the default settings.

**Comment by yermak** [comment]
will have a look shortly

**Comment by yermak** [comment]
Fixed. Will be released in next version.
