### ISSUE TITLE
Program-breaking bug

### ISSUE THREAD

**Issue by Doshilol** [yermak/AudioBookConverter#6]
Hello, I've been using your app and it's absolutely perfect, having no alternative. But recently I've tried to convert another book and now I just simply can't press "File" or "Folder" buttons in "Add" Menu, Drag and Drop doesn't work either. Tried reinstalling Java runtime, compatibility mode, different latest versions - nothing helped. What can be done to fix this? Thanks.

**Comment by yermak** [comment]
Hi, could you please give a bit more details. 
What version of application do you use?
Is this issue related to one specific book or is app broken completely for every book?
Is issue appears on first conversion? Or did not try to convert second book?
It would be great it you describe your sequence of actions in more details.

Looking forward to  help.

**Comment by yermak** [comment]
Thanks, for sharing details.
You are right there is a bug - directory with last converted book is removed. Apps is trying to open it.
I will fix it a bit later - here 3 options to workaround:
1) Go to C:\Users\Your_User_Name\AppData\Roaming and remove AudioBookConverter-V2 directory.
2) Remember which book was you last successful and return source to original place.
3) Wait couple of days - I will release a fix.

**Comment by Doshilol** [comment]
Yes, the first one helped, thanks a lot. Will be waiting for a fix on your great app.

**Comment by yermak** [comment]
Should be solved now.
