### ISSUE TITLE
since AudioBookConverter-6.4.2 and 6.5.0 program no longer starts

### ISSUE THREAD

**Issue by Hardito** [yermak/AudioBookConverter#603]
Since AudioBookConverter-6.4.2 and 6.5.0. After opening AudioBookConverter.exe the program does not start.  
Applies to Win10 and Win11. 
Best regards Hardy

**Comment by yermak** [comment]
removed the build. will check later today

**Comment by yermak** [comment]
Which build did you use? Just retested Portable version works fine.

**Comment by Hardito** [comment]
I did use the Portable version 6.41, 6.5.0, 6.5.1. When I call the .exe in the .zip I get the following message:
![Audiobookconverter](https://github.com/yermak/AudioBookConverter/assets/61164845/90822004-63e6-42f4-99ec-3074b867e274)

**Comment by yermak** [comment]
Hey,
You need to unpack zip file somewhere and then run exe file from the folder...

**Comment by Hardito** [comment]
When I unzip the zip file and start the .exe, the program doesn't open. There is then no error message. Applies to WIN10 and WIN11.
