### ISSUE TITLE
Drag & Drop not working

### ISSUE THREAD

**Issue by Kazaa3** [yermak/AudioBookConverter#62]
Drag & Drop is not working anymore in 5.1.0.

**Comment by yermak** [comment]
Drag & Drop does work if you dragging file on filelist. You likely are draging file on queue (which become default screen) and files tab is not visible :)
If you add at least one file, then you will be able to drag other files...

But i agree, it's require fixing...

Any ideas? Shall queue just accept drag&drop?

**Comment by yermak** [comment]
This will fixed now.
Drag & drop is now accepted in queue (will open files tab), in files mode (will just add files), in chapter mode (every new drag will create separate part).
Will be released in next version
