### ISSUE TITLE
App freezing

### ISSUE THREAD

**Issue by Kazaa3** [yermak/AudioBookConverter#67]
Sometimes the app is freezing after pressing import :
![3 fail](https://user-images.githubusercontent.com/43350149/79633819-3b04b400-8167-11ea-8dfe-b3e101ba5588.PNG)

**Comment by yermak** [comment]
@HenryMontrose , this relates to the "lag" you mentioned.

Problem appeared as i need to load all meta information from files (mp3, m4b, flac/cue) before chapters could be displayed, this resulted a delay, especially seen if you load files from networks drive and there are many of them...

I took this as next priority.

**Comment by Kazaa3** [comment]
This menu remains with me at runtime until the program is restarted.

**Comment by siteuser42** [comment]
If the delay is unavoidable, I think issue could be alleviated if there was a progress/loading bar to indicate that it is working and not just frozen/crashed. 

Thanks again for your continued development!

**Comment by yermak** [comment]
Progress bar could be a solution or showing that program is loading. Or (which is more complex) do it it more multithered, i.e. start conversion w/o waiting for all informaiton to be ready, this is mostly needed to identify duration of all files to show global progress bar, and secondary to pre-load artwork (but in most cases - single images is used for all files).
I need a bit of time to think what is the best solution
