### ISSUE TITLE
Always select last used file

### ISSUE THREAD

**Issue by Kazaa3** [yermak/AudioBookConverter#68]
If the up or down button was pressed in file mode, the file must be clicked again each time after pressing the button.

**Comment by yermak** [comment]
I can't reproduce it.
Here is what i see on the version 5.1.0
https://youtu.be/eCRTKSPGT9c

**Comment by Kazaa3** [comment]
Sorry Yermark, i can't reprduce it too. But i had t some point this problem.

**Comment by yermak** [comment]
well, it could be the - I'm trying to add more features, don't have much time for testing of all scenarios.
