### ISSUE TITLE
Installation for all Windows Users

### ISSUE THREAD

**Issue by Nepumuk2000** [yermak/AudioBookConverter#69]
Hi,

really appreciate the work you did from the start which I still remember. I realized that the update to version 5 brought a new installation routine which keeps me from installing to a folder below program files. I would like to install AudioBookConverter for all users on one Windows 10 computer - the standard folder offered in the installation routine points to some specific user folder.

I tried to change this to Program Files but still during installation with admin rights I get some "you have no right to access the folder"- message on half way installation.

Are there any possibilities to change this behaviour?

Thank you for your great work!

Best regards
Nepumuk2000

**Comment by yermak** [comment]
@Nepumuk2000, 
Current packager/installer is not very flexible, as they just restored it in Java 14, after being broken in Java 9,10,11,12,13 - and for now the only available.

Installing programs per user is actually good practice recommended by modern systems.
While creating second installer is possible, i can't promisse - it will be on priority list. I will have a look if it makes process more complex.

**Comment by yermak** [comment]
@Nepumuk2000,
I did another custom manual build of version 5.1.0 for all users, could you please have look.
Unfortunately, i have not found the way to let user decide what type of installation he would prefer during the install process, so you need to get right installer upfront.
So, if that what you are looking for, i could do 2 different builds for each release.
