### ISSUE TITLE
Build from source

### ISSUE THREAD

**Issue by gatozee** [yermak/AudioBookConverter#71]
How do I build this from source? I'm using Archlinux so I can't use the Windows and DEB packages.

**Comment by yermak** [comment]
Hi @gatozee,

I assumed you tried `https://www.google.com/search?q=installing+deb+on+arch+linux` and decided to go diffucult path.

There won't be magic script to make it happen, however, please find the manual https://github.com/yermak/AudioBookConverter/wiki/Building-from-source
It will require some linux knowledge and knowledge of java/maven will be helpful, but not mandatory. Process become quite complex as Oracle decided to move JavaFX (this is UI framework i selected couple of years ago when they decided to include it back to JDK ) outside of JDK.

Will be happy to help you to build from source.
