### ISSUE TITLE
Not combining MP3s 

### ISSUE THREAD

**Issue by aterriblegamer** [yermak/AudioBookConverter#73]
I am not sure what  causes this, but some books I can not create a single M4B. Instead the app creates a seperate M4B for every single MP3. I have created hundreds of books so far, and I cant seem to figure out what causes this with some files.  Any ideas?

I have tried going to chapters mode and combining all the chapters and it still behaves this way.  I have tried setting the Split output by option to both setting (I wish there was a NONE option here)

![image](https://user-images.githubusercontent.com/20670470/82085729-497cb780-96a2-11ea-9ba1-f5e291741269.png)

**Comment by yermak** [comment]
That's very interesting. It would be helpful if you could show screenshot after importing chapters... Is it repepatable on the same files?
The logic of splitting is very simple and strighforward, by default it split by parts and normally there is just one part - you should have single file.
If you change splitting mode to chapter it would create m4b per mp3, however, it's not your case...
From what i see on the screenshot, somehow it created 30+ Parts.
Could you clarify how did you add files to program? by files or by folder? in single go or one-by-one...

**Comment by yermak** [comment]
@aterriblegamer, please try version 5.2.0 there were a lot of fixes, your one could be resolved.

**Comment by Aegiswiz** [comment]
5.2 IS the problem. All previous versions combined multiple mp3 files into a single m4b file with tags for chapters. Best program there WAS for such things.  I made 5.2 work once after 5 hours and thought OH... just import, close the arrow so only the top is showing and it will work.  Not so much.  Is it possible to download versions that worked?  V3, v4? I deleted the old install file. That won't happen again.

**Comment by Aegiswiz** [comment]
I just wish I could download v3.2.  These improvements have made this program entirely too much trouble... never did get it to work.  I'm talking 5.2 btw.  It's exactly as aterriblegamer says.  Can't make that thing work.  Only thing it does now is convert mp3 files to individual m4b files.  The defaults are crazy too. 

I added by files, by folder, combined, edited, changed default settings.  Once when I "closed" the top file after importing files already added, it did work.  But that was an anomoly I couldn't re-create.... had the chapter names wrong and went to a great deal of trouble to get them right on that one... I'd like to know if you'll allow older version downloads.  Can't find any old "working" versions.

**Comment by yermak** [comment]
If you prefere older version, please go there https://github.com/yermak/AudioBookConverter/releases and scroll down - all versions are available.

On the subject: One of the obvious reasons - you selected "Breakdown output by CHAPTERS", this will create multiple m4b files. the right answer is to use "Breakdown by parts"

**Comment by HenryMontrose** [comment]
Honestly I have to agree with Aegiswiz, you are adding far too many unnecessary bits to it, the beauty of 4.30 and in fact the original concept by Florian Fankhauser was to change mp3's to a single mp4b. for ipods. no more no less. all these wonderful extras like flac , chapters , might be 2020, but really, too much.. I have gone back and am staying with 4.30 which in my opinion, was perfect, all the scaling was correct, now it still goes off the page .. thanks for your heroic efforts, but I know if it ain't broke don't fix it.. is the best way

**Comment by siteuser42** [comment]
I strongly disagree. The program is far more useful now, and I appreciate all the time spent addressing user feature requests and issues.

**Comment by aterriblegamer** [comment]
I have converted many books since I opened this issue, but I have not recreated this issue. I will close for now and reopen if I have a specific set of files that can reproduce the issue.
