### ISSUE TITLE
Uninstall from Control Panel fails for Admin user.

### ISSUE THREAD

**Issue by aterriblegamer** [yermak/AudioBookConverter#74]
I went to uninstall and reinstall the app to see if I could fix some other issues. I get this messgae when trying to uninstall from Control Panel. I am an admin on this box. OS is Windows 10. 

Uninstalling version 5.1

![image](https://user-images.githubusercontent.com/20670470/82086397-52ba5400-96a3-11ea-833f-e116deca3976.png)

**Comment by aterriblegamer** [comment]
I had to re-download the installer and use that to complete the uninstallation

**Comment by yermak** [comment]
@aterriblegamer,
Unfortunately, i can't reproduce your issue. Tried on my local pc as well as in Windows Sandbox in both cases delted installer prior to uninstall, both times were successful.
I assume it's temporarty glitch, caused that installer generator provided by OpenJDK is still in Incubator, thus it may not work correctly. There is nothing I could fix at the moment.
