### ISSUE TITLE
In response to your note re 5.2.

### ISSUE THREAD

**Issue by HenryMontrose** [yermak/AudioBookConverter#76]
Gave it a serious workout, added15 books in a row, didn't realise you could batch convert, worked flawlessly , all I would like to know is that even when I merge all the chapters, and it converts into 1 , when it drops into my ipod touch, it seems to revert  into chapters (B), what I like is (A) all in one..,I thought the whole idea of the ipod  was 1 book 1 file ..
Great work 
Best regards
![20200531_101501](https://user-images.githubusercontent.com/61348379/83539952-99a3a880-a4ef-11ea-939d-9b0b3ed5907f.jpg)
![20200531_101343](https://user-images.githubusercontent.com/61348379/83539958-9b6d6c00-a4ef-11ea-8737-54c6e58ac5f6.jpg)

**Comment by yermak** [comment]
@HenryMontrose,
I'm not entirely sure what you would like to achive... Let's see if we could figure it out...
1) Yes you could add books to queue and they converted while you configure others, that's was introduce in version 3.0
2) You are almost right the whole point of M4B (ipod books) was to have 1 file - 1 book. However, there are exceptions if books are long and quality is high then old version of ipods can't handle such large files and you may need to split them in Parts (Part is not equal chapter) - Having a "Part 2" will result having second file (iphone shows them as single book, can't test on ipod any more). Also, services like Audible also do it to allow download book by parts.
3) If you would like to see chapters in the books on ipod like on picture 2 you need to see all those chapters in the program - you merged all source file into single chapter you likely will see picture 1. For most of the books 1 source file equal 1 chapter, however, somethimes there are exceptions like file01_1, file01_2, file01_3, where chapater is split by source files, only in this case you need to merge them into single chapter. In most of the cases you could leave it as is.

Also you can skip importing chapter completely and program should behave as in original version just merge all files into 1 for ipod.

**Comment by yermak** [comment]
I hope issue is closed
