### ISSUE TITLE
Start button stopped working

### ISSUE THREAD

**Issue by WillyWonksters** [yermak/AudioBookConverter#77]
After using your program for probably 15 books back to back, it suddenly stopped working. I have no idea what changed. 

Any suggestions?

**Comment by siteuser42** [comment]
Are using the installed or portable version? I try portable if you are not already using it.

**Comment by yermak** [comment]
@WillyWonksters ,
Did restart of the program help?

**Comment by WillyWonksters** [comment]
No.

I tried restarting the computer, re-extracting the portable, deleting temp data, installing the non-portable version. 

Still nothing.

**Comment by yermak** [comment]
@WillyWonksters,

Could you please delete all installations, then install Portable version in some location (i would recommend - use new one for clearity). Run portable version, add one or several files. Press start button.
Assuming it did not work, please go to installation directory and find file AudioBookConverter.log.
Attach this file here (there is no personal information, only names and path to your files).
Let see if we could fix it remotely.

**Comment by WillyWonksters** [comment]
I downloaded your latest version and it is working again. I'll follow your request if I see this issue again.
