### ISSUE TITLE
More options in chapternaming

### ISSUE THREAD

**Issue by abuhamsa** [yermak/AudioBookConverter#78]
![image](https://user-images.githubusercontent.com/1926397/87776195-af62f800-c827-11ea-8cdb-e41596b659ee.png)
There is this tiny little dot "." that is mildly infuriating for me just as I dont like it at the end.

Could you make like options to set this point or not set it?

The string where the dot gets set is in renderChapter: https://github.com/yermak/AudioBookConverter/blob/master/src/main/java/uk/yermak/audiobookconverter/Utils.java 

Or even something like a textbox where we could use Tags to set our chapternaming:
<book no> - <book title>: Chapter <chapter no>

This would look like:
01 - Harry Potter and the Philosopher’s Stone: Chapter 001

With a solution like this we could use what ever we want between the tags.

**Comment by yermak** [comment]
Hi,
Tiny little dot "." could be fixed without code modification.
Template is fully customisable and located in C:\Users\[USERNAME]\AppData\Roaming\AudioBookConverter-5.2.0\AudioBookConverter-5.2.0.properties 
search for field **chapter_format** and dot which you concerned with is here <CHAPTER_NUMBER>**.**
You could customise your temlate even more using documentation from here https://github.com/antlr/stringtemplate4/blob/master/doc/index.md

From the top of my head template you are looking for is here
chapter_format=<if(BOOK_NUMBER)><BOOK_NUMBER> - <endif><if(BOOK_TITLE)><BOOK_TITLE>: <endif><if(CHAPTER_TEXT)><CHAPTER_TEXT> <endif><if(CHAPTER_NUMBER)><CHAPTER_NUMBER> <endif><if(TAG)><TAG> <endif><if(CUSTOM_TITLE)><CUSTOM_TITLE> <endif><if(DURATION)> - <DURATION><endif>

just replace existing field

You can remove file completely (if you break it) and it will be recreated by program.

I don't won't to add this to UI settings of the program as very little people will use it, however, i may need to add it FAQ somewhere.

**Comment by abuhamsa** [comment]
hi ty for you fast answer. this solution is great. just didnt know about it.
so maybe a referenc in your read me or something would be great. 

but for me this issue is solved.

**Comment by siteuser42** [comment]
Is there anyway to use this properties template to always default to filename for chapter? I tried <filename> and <file_name>

That's what I always use, and it's pretty tedious to always edit chapter and uncheck all three boxes, switch to filename, then check "apply to all" each time, since the boxes reset to checked for each book. 
Thanks!

**Comment by yermak** [comment]
@siteuser42, that's very good idea.
Creted new issue for this https://github.com/yermak/AudioBookConverter/issues/79
