### ISSUE TITLE
Autodetect max bitrate and channels

### ISSUE THREAD

**Issue by thew1se** [yermak/AudioBookConverter#80]
Hi Thanks for making a great program!

I just converted a set of mp3s which were 1gb to m4b which ended up as 2gb.  Is there a way to detect and maintain the original quality so the file size does not become large?

**Comment by aterriblegamer** [comment]
Please verify the source bitrate and frequency. I have noticed the app does not detect source values and defaults to outputting 128/44100. If your source is lower than that it will create a much larger file with no increase in quality.

**Comment by thew1se** [comment]
the source files are 69kbps, the target was 128.   Thanks I will retry.   

It would be nice if there was a "maintain bitrate" option, or at least a display bitrate of imported files so we can see what we are changing.  :)

**Comment by yermak** [comment]
Hi all,
Earlier version used to have this option - detect bitrate and autofill it, but then I changed the way I work with files and feature was removed.
I will add this to my todo list, it may not work for all formats...

Practically if you go from mp3 to m4b you could go with lower bitrate and you would not notice difference (for audiobook).
Or switch to ogg (if you on android) and you could go even lower bitrate.

Consider looking to FAQ - you may found usefull tips https://www.recoupler.com/products/audiobookconverter/faq#h.khrt6mlim5wh
