### ISSUE TITLE
Play/Pause button does not work in Chapter mode

### ISSUE THREAD

**Issue by thew1se** [yermak/AudioBookConverter#81]
I select the file then click play....nothing happens.  Just downloaded so using newest version (5.2.0 for all users).

Edit:
Actually the button only works in file mode and not in chapter mode.....not sure if that is by design or not but would be nice if chapter mode worked too.

**Comment by yermak** [comment]
Yes, it's known issue - works only in file mode.
Still on my todo list.

**Comment by thew1se** [comment]
ok.

This may be related to the play/pause button stopping working when chapter mode is activated. But result is that can't stop the playback either....which may have been unknown.

After adding a folder:

1. click a file
2. press play/pause button (sound is playing from this point forward)
3. press import
4. edit as needed
5. press start
6. add next folder
7. click import 
8. press play/pause.....does not stop.

**Comment by yermak** [comment]
Thanks. That's expected.
I originally added play to preview files as sometimes names and tags could be so bad, so need to listen each file separately to order them. 
Probably solution could be stop playing after starting conversion... I will think about that...

**Comment by stormdb** [comment]
Fixed in PR #135

**Comment by stormdb** [comment]
Closes yermak/AudioBookConverter#81

**Comment by yermak** [comment]
Fixed
