### ISSUE TITLE
Possible to put custom field for "Chapter"

### ISSUE THREAD

**Issue by thew1se** [yermak/AudioBookConverter#82]
Because many of my books mp3s are not organized by chapters, rather parts, I would prefer to name them quickly to Part 1, Part 2...etc.

Only current way to do this is manually for each file.  Can become tedious for books with many files.

Possible to put a custom field in the place of Chapter?  Or choose the location of where the current custom field goes?

Just a nuance for me, I'd prefer not to have a period after the chapter number...  :)

Thanks again for a great program!
<img width="695" alt="Capture" src="https://user-images.githubusercontent.com/57738712/88199605-1101d880-cc13-11ea-8c58-e193c192d7b9.PNG">

**Comment by yermak** [comment]
Please have a look to issue #78 
I believe you could use the same soluton.
In your case you need replace <CHAPTER_TEXT> with word you like i.e. Part...

**Comment by thew1se** [comment]
Ok thanks I will have a look.  If you have time, this would be a nice integrated feature. :)

**Comment by thew1se** [comment]
Hi, so tried this out, I found the properties file and I got rid of the "." by simply deleting the dot in the correct place.  
But I'm stumped on how to change the "Chapter" field I circled above.  I know very little about programming, (just enough to be dangerous).   Can you advise the text to update/replace?   From Properties file:

```
#
#Thu Jul 23 10:21:39 EDT 2020
part_format=<if(WRITER)><WRITER> <endif><if(SERIES)>- [<SERIES><if(BOOK_NUMBER)> -<BOOK_NUMBER><endif>] - <endif><if(TITLE)><TITLE><endif><if(NARRATOR)> (<NARRATOR>)<endif><if(YEAR)>-<YEAR><endif><if(PART)>, Part <PART><endif>
chapter_format=<if(BOOK_NUMBER)><BOOK_NUMBER>. <endif><if(BOOK_TITLE)><BOOK_TITLE>. <endif><if(CHAPTER_TEXT)><CHAPTER_TEXT> <endif><if(CHAPTER_NUMBER)><CHAPTER_NUMBER> <endif><if(TAG)><TAG> <endif><if(CUSTOM_TITLE)><CUSTOM_TITLE> <endif><if(DURATION)> - <DURATION><endif>
genres=Audio Book\:\:Fantasy\:\:Fiction\:\:Non-Fiction\:\:Audiobook
output.folder=*******
source.folder=*******
filename_format=<WRITER> <if(SERIES)>- [<SERIES><if(BOOK_NUMBER)> -<BOOK_NUMBER><endif>] <endif>- <TITLE><if(NARRATOR)> (<NARRATOR>)<endif>

```

**Comment by yermak** [comment]
I believe you could just find text `<if(CHAPTER_TEXT)><CHAPTER_TEXT> <endif>` and replace it with `<if(CHAPTER_TEXT)>Part <endif>`

**Comment by thew1se** [comment]
Thanks will try

**Comment by thew1se** [comment]
this worked great!  Thanks!
