### ISSUE TITLE
Customize chapter title is pulling Album when Title is selected

### ISSUE THREAD

**Issue by aterriblegamer** [yermak/AudioBookConverter#83]
Here are my MP3 Tags

![image](https://user-images.githubusercontent.com/20670470/88211906-3b4f9800-cc0b-11ea-9368-06175f1ae90d.png)

When I go into ABC 5.2.0
Add one of these file
Import Chapters
Edit Chapter
Choose Title from the MP3 Tag dropdown.
BUG:  The Album Tag is used instead of Title

![image](https://user-images.githubusercontent.com/20670470/88212016-6afea000-cc0b-11ea-9e3e-8f602bc94ba1.png)

Choosing Album also shows the  Album information

**Comment by yermak** [comment]
Hi,
Noted, it's result of fixing #52
Will fix it shortly

**Comment by yermak** [comment]
Fixed  and will be released in v5.3

**Comment by aterriblegamer** [comment]
Is there an estimated timeline for 5.3?
