### ISSUE TITLE
Improvement Request - File order on import by number value, not alphabetical order

### ISSUE THREAD

**Issue by thew1se** [yermak/AudioBookConverter#86]
I just imported a book very poorly organized with folder numbers and file numbers which did not have zero placeholders:
For example:

1 filename.... instead of..... 01 filename
2 filename.... instead of..... 02 filename
3 filename.... instead of..... 03 filename

As a result when the files imported the file order was all incorrect because it organised them in alphabetical order.
For example:

10 filename
1 filename

Can they be imported by number value first instead of alphabetical order?

Also, I tried to organize them in the program, but could not move around multiple files at once.   So doing one at a time would take a very long time......bug?

**Comment by yermak** [comment]
@thew1se 
I faced a few such books as well, this is not very strightforward to implement and may lead to confusing behavior, i.e file name really starts with number as part of file name
Moving more files at once could be done - never had intention to have this feature.
In you scenario - i would move file "10 filename" down, then "20 filename".

I will keep this issue open, to see if there is good and not confusing solution

**Comment by yermak** [comment]
This actually duplicates #48

**Comment by yermak** [comment]
Fixed in 5.5.7
