### ISSUE TITLE
Bug - Importing *.m4b creates duplicate chapters...can't see file source

### ISSUE THREAD

**Issue by thew1se** [yermak/AudioBookConverter#89]
I have a book with 2 m4b files (part 1, part 2).  When I clicked add file it looked like this:

<img width="755" alt="Capture1" src="https://user-images.githubusercontent.com/57738712/89127967-07545c80-d4c0-11ea-9d68-61af97b6b4cb.PNG">

After clicking import and expanding the files it looks like this:
<img width="963" alt="Capture" src="https://user-images.githubusercontent.com/57738712/89127973-13401e80-d4c0-11ea-993f-a6c0cfcc378a.PNG">

So not sure what's going on...is part 1 actually already split into chapters and its reading the chapter info?  or is this a bug?

**Comment by yermak** [comment]
Hi,
If you are importing m4b file, it's very likely those files already contain chapter info and program re-import them.
You should be able to edit chapter information and create new book (in one or more parts).
Unfortunately you can't do custom chapter duration, you could only merge and rename them.

Also, this screen should not appear, i can't repruduce on current beta of 5.3.0.

Please be patient 5.3.0 is comming
