### ISSUE TITLE
Source files are not shown when importing existing m4b

### ISSUE THREAD

**Issue by yermak** [yermak/AudioBookConverter#90]
After importing m4b files, now details is shown in tracks (within chapters)

**Comment by slickwell** [comment]
when you merge, how come on the audiopod, there are chapters......the idea is 20 files merge into 1, not actually sure what this has achieved... I am sorry but Florians MP3 to iPod/iPhone Audio Book Converter works.... your started well.. but is now too much  ever heard of KISS

**Comment by yermak** [comment]
@slickwell, Not sure what your comment refers to...

You still could do exactly same scenario as with Florians programs, add files, press start, get result (much faster).

You don't have to use those features which you don't need :)

**Comment by slickwell** [comment]
As I mentioned. I like you software ,however you have moved far too far to try and please everyone, and in turn, you want to add far too many boxes, and the scale has shot through the roof.. you can no longer add genre as there are too many boxes. with all the stuff... I guess most people want to download mp3's, and convert them into a single m4b file to add to ipods etc... , who wants to split it into chapters, when ipods remember where you were... all this flac wav nonsense.. audiobooks are usually read by 1 person, and don't need a massive kpbs... ,9 times out of 10 are better in mono.. and that is all I meant by Florian..., that's all his primitive did, yours is neater and much much quicker.. but it needs to be rescaled completely to become really useful.... and also it needs to be able to convert to 1 only, not different chapters as per artwork I have sent you before  . it needs to be wider, not higher.. you have all  the width, but you seem to want to cram it all into height...

Good luck to you and congrats on your sheer ingenuity  and patience 


-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


27 Aug 2020, 06:39 by notifications@github.com:

**Comment by yermak** [comment]
@slickwell 
Thank you for feedback. I'm still trying to keep program UI as simple as possible so user don't need to configure much.
With UI not fitting into screen, let me give it another go in next release, i will see if i could make it more compact - this is is windows scaling issue - as on my screen it fits perfectly well.

**Comment by slickwell** [comment]
I really appreciate it, but you cannot see the bottom or adjust it.. in other words you cannot add genre , you cannot delete artwork if there are two, and you cannot specify the kpbs.. otherwise great.. guess you need to go wider  instead of longer.. 
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


29 Aug 2020, 08:19 by notifications@github.com:
