### ISSUE TITLE
Fit 14 inch screen and remember position and size on exit

### ISSUE THREAD

**Issue by slickwell** [yermak/AudioBookConverter#92]
Seems to work well, however scaling is still an issue, you solved it in the earlier ones, but since you added so many boxes, it is far too tall.. it does not fit in anything smaller than 15 inches.. and even if one moves it  it is not sitting comfortably, if you widen it it does not remember the position and this has to be altered every time
![5 3 1](https://user-images.githubusercontent.com/69924049/90724550-a944b900-e2b6-11ea-81bc-6c65041f7725.png)
It is now so tall, the boxes at the end:, narrator, genre, no longer appear......Hey yermak, these need addressing..  I have looked at the issues.. and even you agreed with a previous person, that scaling was important.... otherwise.. its like having a chocolate teapot...

**Comment by yermak** [comment]
UI was reworked and fixed in 6.4.1
