### ISSUE TITLE
Feature Request for bitrate customize

### ISSUE THREAD

**Issue by dangnhapmoiluc** [yermak/AudioBookConverter#93]
Thank you for your very good software,
Could you please add the feature for bitrate customize when we choose "Variable bitrate, Quality"?

**Comment by yermak** [comment]
Hi, could you explain in more details.
In "Variable bitrate, Quality" mode you need to select one of quality preset 1 to 5.
![image](https://user-images.githubusercontent.com/380491/90871972-d2874700-e393-11ea-9467-42f57b012275.png)
In this mode you can't configure bitrate - bitrate will be variable.

**Comment by dangnhapmoiluc** [comment]
Thank you for your information,
We would like to compress the size of audiobook file, so the bitrate will be variable, but maximum bitrate is within limited setting bitrate. Please see example as below photo:
![image](https://user-images.githubusercontent.com/39268702/91118540-62daca00-e6bb-11ea-9719-23fc4dd0a1ae.png)

**Comment by yermak** [comment]
@dangnhapmoiluc,
I'm not sure which program it is, however, at the best of my knowledge - this is not supported by feature by aac codec.
I think this behaviour could be achived by firstly re-encoding to 24kbps and secondly re-encoding to VBR, however, I believe quality it will not make much benefit from quality perspective. If you really need low bitrate go for ogg (opus) format.

Please look into this document https://trac.ffmpeg.org/wiki/Encode/AAC (VBR section)

There are 3 main encoders to AAC:
FFmpeg (which i use)
Fraunhofer (which has licencing limitations)
Apple

Unless this program uses something very unique, they probably just don't use one of parameters.

**Comment by dangnhapmoiluc** [comment]
Thank you so much for your support,
We used to convert audiobook by "Chapter and Verse" from Loden Software, this software will run together with iTunes, and after convert with 24kbps and VBR, the quality of audiobook is still good & size is very small. Unfortunately, iTunes does not support this program anymore, that why we would like to ask your help, hoping that you could add the feature for bitrate customize someday.
Once again, thank you for very good software,

**Comment by yermak** [comment]
Hi,
I can't promiss to implement this feature in near future.
I community would support this may be implemented

**Comment by yermak** [comment]
Just for the record.
Indeed Apple AAC codec support CVBR for m4b - variable bitrate with constraint on bitrate.
However, I can't find the way to implement it in open source version.

OGG and MP3 codecs support this feature - I have not implemented its support yet, but I may do this in the future.

**Comment by dangnhapmoiluc** [comment]
Thank you for your information,
We will be very glad to see this feature be implemented by you in the future.

**Comment by yermak** [comment]
there is no much interest from community to implement this feature.
Also I won't be able to make it for aac codec, so this won't be fixed
