### ISSUE TITLE
Queue finishes with "Error!", no output

### ISSUE THREAD

**Issue by d8xa** [yermak/AudioBookConverter#94]
When trying to convert a list of MP3 files into a M4B, it seems to complete the last step "Merging chapters", but then stops at "Estimated time remaining: 00:00:01" and above the progress bar it just says "Error!"

__Input__: 781 MP3 files, 1 JPG file.
__OS__: Windows 10
__Log__: [AudioBookConverter.log](https://github.com/yermak/AudioBookConverter/files/5147130/AudioBookConverter.log)

This

```
30-08-2020 18:23:51 ERROR Mp4v2ArtBuilder:386 - Poster Error: ERROR: unable to open C:\Users\Me\Downloads\Sturmlicht06\Brandon Sanderson - Die Splitter der Macht (Die Sturmlicht-Chroniken 6) [ungekürzt]\Sanderson_BSplitter_der_Macht_DL_ungek_194694.jpg for read: No error
```

and this

```
30-08-2020 18:23:51 ERROR Mp4v2ArtBuilder:382 - Failed to apply art work
uk.yermak.audiobookconverter.ConversionException: ArtWork failed with code 1!=0
	at uk.yermak.audiobookconverter.Mp4v2ArtBuilder.updateSinglePoster(Mp4v2ArtBuilder.java:60)
	at uk.yermak.audiobookconverter.Mp4v2ArtBuilder.coverArt(Mp4v2ArtBuilder.java:32)
	at uk.yermak.audiobookconverter.ConversionJob.run(ConversionJob.java:90)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.Error: ERROR: unable to open C:\Users\Me\Downloads\Sturmlicht06\Brandon Sanderson - Die Splitter der Macht (Die Sturmlicht-Chroniken 6) [ungekürzt]\Sanderson_BSplitter_der_Macht_DL_ungek_194694.jpg for read: No error

	... 6 more
```

seem to be the relevant parts of the log. Apparently it fails to read the artwork file, but it's not clear why.

**Comment by yermak** [comment]
Hi,
It's very likely that tool i use for art work - mp4v2 does not support non-ansii characters.
I would recommend to rename folder containing "ungekürzt" to something else and retry.
That's the only idea i have now.

Please let me know if it works.

**Comment by 79x3AY2c** [comment]
Thanks, it worked after renaming the folder!

**Comment by yermak** [comment]
I will keep issue open. As i know how to workaround it - as I knew about it before.
I had the idea to fix it, but there was something more interesting to do :)

**Comment by yermak** [comment]
@79x3AY2c ,
Could you please advise how did you add art work file to the conversion.
I believe you either manually added it or pasted it, as it seems I fixed bug with non-ansii characters for artwork in mp3 folder.

**Comment by 79x3AY2c** [comment]
Yes, I added it manually.
And it seems like it already works in the current version when the artwork is added with the folder.
Only when I add it manually, the error occurs.

**Comment by yermak** [comment]
Thanks for confirming.
That what I expected - I fixed it earlier for artwork within folders and artworks from mp3 files, but only now fixed for manual addition of artwork.
Will be released in next version.
