### ISSUE TITLE
Number of chapters limited to 255

### ISSUE THREAD

**Issue by jolynsbass** [yermak/AudioBookConverter#95]
I know this probably a rare issue, but I've got a recording of Les Miserables that splits into 375 chapters! When I join the file into an m4b with your program, the first 254 chapters are perfect, but chapter 255 is one big 20 hour chunk (the rest of the book.)

Is this a hard limitation with the m4b file spec, or did you just program it expecting that no-one would ever need more than 255 chapters? In other words, is this an easy fix (programming), or impossible(file spec)?

Thanks!

**Comment by yermak** [comment]
Hi,
Honestly speaking I never tried such number of chapters - i will need to research it.
As a workaround I suggest to break book into several parts, to ensure that number of chapters do not exceed 255 in single part.

**Comment by yermak** [comment]
BTW, you could check if those files are real chapters. Or singe chapter is split over several files.
I have following book for example, and that's where I use "combine" feature to get single chapter from several files.
![image](https://user-images.githubusercontent.com/380491/91822969-71cbfa00-ec30-11ea-92d4-6c89f30a9e7d.png)

**Comment by jolynsbass** [comment]
Thanks for the suggestion! A little research revealed that the book really does have a bit under 400 chapters, but that it was also published in 5 discreet volumes - I can use each of those as a "part", and then each will fit easily under the 255 chapter limit per file.
Have a great day,
Dave

________________________________
