### ISSUE TITLE
Bug: File never finishes - Stuck at "Merging Chapters"

### ISSUE THREAD

**Issue by thew1se** [yermak/AudioBookConverter#97]
Just converted about 10 books.  One of the files is stuck at "Merging Chapters".

<img width="845" alt="Capture" src="https://user-images.githubusercontent.com/57738712/92167165-ec02a700-ee07-11ea-8cb6-53f5713d22b7.PNG">

**Comment by yermak** [comment]
Is it repeatable?
If you could send me log file it may help.

**Comment by thew1se** [comment]
It happened a couple times with the same book while converting multiple books at the same time. 
[Log.zip](https://github.com/yermak/AudioBookConverter/files/5176250/Log.zip)

It did not happen when I tried on the 3rd or 4th attempt after closing and opening program and only doing the one book.

**Comment by yermak** [comment]
Honestly, it's impossible to diagnose the error on such large log file.
If you could do clean cut it may help, or if you solved the issue - i would recommend to move on, as there is new version is comming.
