### ISSUE TITLE
Pressing "Start" Button doesn't work. Nothing happens.

### ISSUE THREAD

**Issue by Awedamm** [yermak/AudioBookConverter#98]
Thanks for this amazing program. It has saved me so much time.
However, all of a sudden, the start button just stopped working yesterday. I tried using the keyboard shortcut too, but I can't seem to start the conversion.
I tried uninstalling and reinstalling, but the same issue persisted. Any ideas?

**Comment by morejames** [comment]
I am also having the same issue as OP. I'm running windows 10 version 1909.

**Comment by yermak** [comment]
In such case the only solution I could recommend - go to C:\Users\%USERNAME%\AppData\Roaming\AudioBookConverter-x.y.z\
And either share exception with me from your log file or delete configuration file and retry.

**Comment by Awedamm** [comment]
Thank you! Thank you!!!
I deleted the config files like you said, and it works perfectly now.

> In such case the only solution I could recommend - go to C:\Users%USERNAME%\AppData\Roaming\AudioBookConverter-x.y.z
> And either share exception with me from your log file or delete configuration file and retry.
